### ISSUE TITLE
Get AppEngine deployment URL at runtime

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#10]
URLs used in the manifest are hardcoded here:
https://github.com/foolip/mdn-bcd-collector/blob/9c26f56b10fcb1ca47dc92101531c2547d4aaf5e/app.js#L41

This makes it impossible to collect results from a staging instance:
https://github.com/foolip/mdn-bcd-results/pull/105

Probably https://cloud.google.com/appengine/docs/standard/nodejs/runtime#metadata_server is how to get the URL of the instance. @Hexcles do you know how wpt.fyi does this?

**Comment by Hexcles** [comment]
@foolip the Go `appengine` package provides a helper function for it, which I'm pretty sure simply constructs the URL by concatenating project ID and `.appspot.com`.

**Comment by foolip** [comment]
@Hexcles do you know the lines of code where this is done? If I know the name of the Go binding maybe I can find if there's an equivalent for NodeJS.

**Comment by Hexcles** [comment]
@foolip see the code around here:
https://github.com/web-platform-tests/wpt.fyi/blob/8ab7e1b72bec05da62f700f85966fd15c138d4c3/shared/appengine.go#L162
