### ISSUE TITLE
Support manual tests that won't work in automation

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1010]
https://github.com/foolip/mdn-bcd-collector/pull/1008 deleted some custom tests that didn't work in Edge 12-18, losing some useful tests. To bring back this kind of test, we'd need to mark them up as manual and avoid running them when collecting results using WebDriver.

**Comment by foolip** [comment]
@vinyldarkscratch points out an alternative in https://github.com/foolip/mdn-bcd-collector/issues/1007#issuecomment-784764010, simply skipping certain tests in automation.

**Comment by queengooborg** [comment]
I think it's safe to say that we've pretty much fixed this one using an ignore list to ignore specific tests during automation.
