### ISSUE TITLE
Test for javascript.builtins

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1056]
Looking at #917, there's a number of missing JS builtins.

It feels like this should be relatively easily to add support for, as by and large there's nothing different to how we test for apis. To get full coverage will require a larger number of custom tests, but that again is no different to apis.

**Comment by foolip** [comment]
This is probably possible, but without a machine-readable definition of all JS APIs I'm not sure how to generate the tests. For example, what tells us that `Array.isArray` is a static method but `Array.prototype.forEach` is on the prototype?

**Comment by foolip** [comment]
I've taken a look at https://tc39.es/ecma262/#sec-array-objects and can't find anything in the source or the output that seems intended to be machine readable, although the section names are very regular and one could probably get quite far just from the ToC of the spec.

But it also looks like one can infer some things from the MDN pages:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

The title of the latter is `Array.prototype.forEach()`, which solves the first problem.

@Elchi3, do you know if there's any data behind this on MDN, or if there's machine readable data for the JS spec itself?

**Comment by foolip** [comment]
I've also asked in https://es.discourse.group/t/is-the-api-surface-of-the-spec-machine-readable/699 if there's something one could use here.

**Comment by Elchi3** [comment]
Relying on page titles is not a good idea because there is valid criticism about them and we are looking into changing them. See https://discourse.mozilla.org/t/incorrect-titles-for-method-property-articles

I don't think we gathered data on this. It would be good to structure MDN docs reliably so that information like you want here is obvious to the reader and accessible to the machines.

For now, my guess is that getting this info from the specs is best (there are multiple ECMA specs, but they seem to be quite consistent).

**Comment by foolip** [comment]
That was a lively thread for a few months in 2018 :)

I'm not sure if anything is still planned, but good idea to not depend at all on MDN page titles. Scraping spec headings seems more promising.

**Comment by gsnedders** [comment]
One question is whether we can leverage the data/tests from https://kangax.github.io/compat-table/ (i.e., https://github.com/kangax/compat-table), which also has links to MDN for many things (though that doesn't necessarily help with where it should appear in BCD).

**Comment by foolip** [comment]
This has been fixed over a number of PRs and I've just cut a new 3.2.0 release for it. Tests are here:
https://mdn-bcd-collector.appspot.com/tests/javascript/builtins
