### ISSUE TITLE
missing api.HTMLAnchorElement.toString

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1057]
Somehow we aren't generating a test for the stringifier

**Comment by foolip** [comment]
I've noticed this as well, and it also affects api.HTMLAreaElement.toString.

The problem is in `flattenMembers`, where attributes with `member.special === 'stringifier'` are not handled. It looks like there are more cases like this, but those `toString` entries aren't in BCD.

**Comment by foolip** [comment]
Ah, and trying to fix this runs into https://github.com/foolip/mdn-bcd-collector/issues/841, because `"toString" in HTMLAnchorElement.prototype` is not a good-enough test for this.

**Comment by foolip** [comment]
The generated test should rather be `HTMLAnchorElement.prototype.hasOwnProperty("toString")`, and I think this would be best handled in `buildIDLTests`.
