### ISSUE TITLE
Add support for __additional to css.properties

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1059]
There are large numbers of children of css.properties.* in BCD, and it would be good to add some coverage for them. The most common case is keywords as values, but that's far from the only case (e.g., `gap` in different layout modes), and in general I think parsing the value syntax is difficult and doesn't necessarily suffice (e.g. `list-style-type` takes any counter-style, and we want to test support for each predefined counter style).

**Comment by foolip** [comment]
There's a lot of overlap between this issue and https://github.com/foolip/mdn-bcd-collector/issues/705, which is specifically about keywords.

I tried something a few days ago which wasn't super encouraging. What things are in BCD is probably somewhat haphazard, so possibly the most straightforward thing here is to just generate a lot of custom tests for this semi-automatically, avoiding the need to get all the details right since one can just skip the hard things.

**Comment by foolip** [comment]
Flexbox `gap` specifically I think can't really be feature detected, see https://github.com/w3c/csswg-drafts/issues/3559

**Comment by gsnedders** [comment]
@foolip Not through pure CSS, no, but it can be through JS (by trying to render something and reading metrics).

**Comment by gsnedders** [comment]
Hmm, maybe it makes sense to add a `__values` option which just takes an array of possible values, where it's presumed that `css.properties.foo.value` is the destination, and leave `__additional` for any more complex cases?

**Comment by gsnedders** [comment]
See also https://github.com/foolip/mdn-bcd-collector/commit/cbb88008adfa4bc90388c52abf56eddb7a421a6b which added support for `css.properties.[foo]` as custom tests, but doesn't allow custom tests at any other level. I'd suggest making `custom-tests.yaml` use `__test` for tests in `css` too. Maybe just allow `__test` anywhere, and then we can start writing tests for `html` or `css.types` or whatever?

**Comment by foolip** [comment]
@queengooborg has added some custom tests for CSS written in JS in https://github.com/openwebdocs/mdn-bcd-collector/blob/45f5d068ee5aa33a460b11ba9a97a57e60b5b0e9/custom/tests.yaml#L4762-L4769

If there are cases that still can't be tested, please file a new issue at https://github.com/openwebdocs/mdn-bcd-collector/issues.
