### ISSUE TITLE
Missing WebKit-prefixed interfaces from WebKit tree

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1064]
All very old, and I think only effect old Chrome support:

WebKitMediaSource
WebKitShadowRoot
WebKitSourceBuffer
WebKitSourceBufferList

**Comment by gsnedders** [comment]
Oh, no, that was very incomplete:

WebKitAnimation
WebKitAudioBufferSourceNode
WebKitAudioContext
WebKitAudioListener
WebKitAudioPannerNode
WebKitCSSFilterRule
WebKitCSSFilterValue
WebKitCSSKeyframeRule
WebKitCSSKeyframesRule
WebKitCSSMixFunctionValue
WebKitCSSRegionRule
WebKitCSSTransformValue
WebKitCSSViewportRule
WebKitDynamicsCompressorNode
WebKitMediaSource
WebKitNamedFlow
WebKitOfflineAudioContext
WebKitOscillatorNode
WebKitShadowRoot
WebKitSourceBuffer
WebKitSourceBufferList

**Comment by foolip** [comment]
@gsnedders are these all interfaces have at some point had their interface objects exposed? I suspect not, since `WebKitAudioContext` was exposed as `webkitAudioContext`, but I don't know about all of these.

**Comment by gsnedders** [comment]
> @gsnedders are these all interfaces have at some point had their interface objects exposed? I suspect not, since `WebKitAudioContext` was exposed as `webkitAudioContext`, but I don't know about all of these.

Don't know.

**Comment by foolip** [comment]
The idea of tracking all APIs supported in any browser, even if not present in BCD, didn't really work out. Only WebKit-prefixed things that are in BCD are now in https://github.com/openwebdocs/mdn-bcd-collector and I don't think there's a practical reason to add those back.

(My original idea was that if we tracked everything, then we could identify new features with a mechanism like https://github.com/foolip/mdn-bcd-collector/pull/1225, catching things that happen to not show up via `@webref/idl`. I never finished the work, and the benefits never materialized.)
