### ISSUE TITLE
Use BrowserStack and Sauce APIs to determine supported browsers

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1199]
https://github.com/foolip/mdn-bcd-collector/pull/1197 reminded me about how we decide which browsers to test using BrowserStack or Sauce Labs, something I tinkered with in 5e3ff32d8d4797a6efbc5609917a0ed52363a2b7.

The current approach is to try to create a driver for each browser+version+os combination, we try to create a driver for it in `buildDriver`, preferring BrowserStack and falling back to Sauce. There are lots of rules which which browsers to skip, OS mapping, and so on. There's also some logic to avoid some remapping that happens on BrowserStack for Edge 12-14.

In 5e3ff32d8d4797a6efbc5609917a0ed52363a2b7 I tried using the APIs for BrowserStack and Sauce, with the approach in mind:
- Enumerate all the configurations supported by BrowserStack and Sauce
- For each browser+version+os combination in BCD, look for a matching config, perhaps with per-browser rules about which service to prefer (Sauce is better for Edge and Safari at least)
- If there is no support for that browser, log that and continue

@vinyldarkscratch WDYT?

**Comment by vinyldarkscratch** [comment]
I like the sound of that, yeah!  We'll certainly need to keep some overrides to declare certain browser versions unsupported since BrowserStack remaps some of them, but using their APIs and storing data about preference makes much more sense!

**Comment by foolip** [comment]
I suspect that BrowserStack only remaps when you try to use something that isn't supported but used to be, I'd be surprised if they list Edge 12 as supported in their API.
