### ISSUE TITLE
UA parser weirdness: displays the UA result of another session when multiple sessions running

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1275]
I'm running through and collecting data for collector 3.1.9, running the Selenium script whilst also running live tests on iOS.  One odd thing I've noticed is that when I'm exporting the test results on the live iOS browser, I'll notice that it says "Detected Browser: Chrome 62", of which I realized happened to be the same browser as the currently-open Selenium session.  What it seems like is that we're not setting a variable for the UA parse results for each individual session, which is probably causing this issue.

Note: this does not seem to affect the test results or their file names, just the web frontend.

**Comment by foolip** [comment]
Could this be the same issue as https://github.com/foolip/mdn-bcd-collector/issues/1049?

**Comment by queengooborg** [comment]
It's the same issue, yes -- I hadn't noticed the existing one, whoops!
