### ISSUE TITLE
Get MediaStream from callback-based navigator.getUserMedia()

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1345]
This came up in https://github.com/mdn/browser-compat-data/pull/11718.

`MediaStream` was supported before `navigator.mediaDevices.getUserMedia()` with prefixed and unprefixed variants of `navigator.getUserMedia()`.

@vinyldarkscratch this isn't straightforward because it also predates support for promises, and requires using both promises and callback in the same test. You added the support for async tests, do you think something can be fit into the existing structure?

**Comment by vinyldarkscratch** [comment]
I don't imagine that it would be too difficult to implement support for both.  After all, the code is designed to switch between promise handling based upon the presence of promise-like functions (`then`, etc.), so if we add an `if` clause and have the test return a non-promise instead, we should be fine!
