### ISSUE TITLE
Use document.createEvent to create event instances we can test with

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1363]
I think I finally found the solution to testing event interfaces!  It appears that there's a method, `document.createEvent`, which creates the appropriate event interface.  We should utilize this for our custom tests.

**Comment by foolip** [comment]
@vinyldarkscratch you'v already added a lot of these in custom tests, is there something more this issue is tracking? Perhaps a burndown list to ensure we have custom tests for all event interfaces?

**Comment by vinyldarkscratch** [comment]
Everything that this would cover has been added already, so other than giving these a quick (re-)test, nothing's left for this!
