### ISSUE TITLE
Tests don't run on Safari 5 on BrowserStack

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1416]
I stumbled upon this problem in https://github.com/mdn/browser-compat-data/pull/12027. Loading http://mdn-bcd-collector.appspot.com/tests/api/WheelEvent in Safari 5 on BrowserStack gets stuck on "Running test for Window..." and never shows any results. In the console there's an error that reads:

> TypeError: Result of expression 'd.prototype[b]' [undefined] is not an object.

I suspect the problem happens in the JSON3 polyfill, although I can't find that exact code in there.

It works on Safari 4 and 5.1.

@vinyldarkscratch do you know what might be happening here?

**Comment by vinyldarkscratch** [comment]
I've changed the title of the issue to reflect the true severity of the issue, where tests don't run altogether on BrowserStack's Safari 5 VM.  I've been able to mitigate this issue by using my own local VM, but I know that not everyone would want to set up PowerPC emulation.  😛 

When this came up, I suspected that it was a conflict with an extension installed on BrowserStack's end.  (There was also the possibility of a difference in patch release that fixed a bug; my VM has Safari 5.0.6 while BrowserStack has 5.0.5; however...)  And just now, performing a little bit of testing, I have confirmed just that.  It appears the Selenium WebDriver extension is causing some conflict with the polyfill, and disabling it gets the tests to run.

**Comment by foolip** [comment]
Is it the JSON polyfill that's causing the problem?

**Comment by vinyldarkscratch** [comment]
It is a conflict between the JSON3 polyfill and Selenium WebDriver extension.  Unfortunately I don't know if it's something we can get resolved, unless we fork JSON3 (or more likely, talk to BrowserStack and see if we can get them to upgrade the Selenium WebDriver).

**Comment by foolip** [comment]
Do we actually need the polyfill? Per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#browser_compatibility Safari 5 should already have `JSON.stringify()`. Perhaps we can load the polyfill only if `JSON.stringify` isn't present?

**Comment by vinyldarkscratch** [comment]
It _should_ only be loading the polyfill functions if and only if it needs to.  We do need it for older browsers to collect their results, so I'm wondering what we can do to resolve this issue.  Hmm...

**Comment by queengooborg** [comment]
Okay, so after further review, this is NOT an issue with the JSON polyfill.  I am getting the same JavaScript error on Safari 5 on BrowserStack with a basic test page that has no JS libraries, or even JavaScript to begin with.
