### ISSUE TITLE
Chrome is often set to null by update-bcd?

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1435]
Came up in https://github.com/mdn/browser-compat-data/pull/12093#discussion_r695169762.  I've been noticing Chrome has been `null` for many APIs for some odd reason.  This has been observed in many WebGL APIs, and HTMLMediaElement.

**Comment by foolip** [comment]
Can you give a specific BCD path where this is happening? If you log the `inferredStatements` for that path, what is it? Most likely it's a complex statement and we don't have any code for dealing with it.

**Comment by queengooborg** [comment]
Found a case in https://github.com/mdn/browser-compat-data/pull/13255#discussion_r740992911...
