### ISSUE TITLE
Switch to ESM?

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1443]
This issue is inspired by https://github.com/mdn/browser-compat-data/pull/12161.  It might be beneficial for us to switch our repository to ESM, since BCD's internals seem to be heading in that direction?  Luckily, ESM can import a CommonJS module (but not the other way around, sadly), so we don't have to wait for BCD to make a switch first.

**Comment by foolip** [comment]
I tried this once and I think the main problem I ran into was with the testing setup. We use proxyquire and that will have to be replaced.
