### ISSUE TITLE
Create a changelog

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1446]
Now that we have more reviewers for PRs created from this project, I think it would be very helpful to include a changelog, which we can link on the collector's page.  I feel that this should involve creating a script that handles the new release process, kind of like the scripts in BCD.

**Comment by foolip** [comment]
Sounds like a good idea, and that script could also make the release process easier!

**Comment by vinyldarkscratch** [comment]
So I have two ideas for how we can implement a changelog, specifically its format:

- Markdown
  - Pros
    - Easily readable as its own file
    - Easy to convert into HTML
    - Can be linked directly to the GitHub page
  - Cons
    - Not as easy to modify via script
    - Not as easy to apply some custom formatting I'm thinking of
- JSON
  - Pros
    - Easy for a script to modify
    - Can load into the webpage with custom formatting
  - Cons
    - Requires additional parsing
    - Changelog _must_ be served on the live site

What do you think, @foolip?  I'm leaning towards JSON myself, but I'm not strong on this!

**Comment by queengooborg** [comment]
Marking this for v4.0 -- this is a super useful change that I think we should work into our next major release!

**Comment by foolip** [comment]
Since a changelog is first and foremost for human readers, I would lean towards Markdown. I don't think showing the changelog on https://mdn-bcd-collector.appspot.com/ itself is important, just in the repo seems fine to me.
