### ISSUE TITLE
Make collector runnable in NodeJS/Deno

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1462]
I think it would be nice to be able to run the collector and obtain results for browser-less JavaScript engines like NodeJS and Deno.  Not a high priority though.

**Comment by foolip** [comment]
@lucacasonato would you use this for maintaining Deno data in BCD if supported?

**Comment by lucacasonato** [comment]
While it might be useful to validate that existing coverage is correct, it wouldn't help much with adding coverage, as the coverage for APIs Deno supports is already at near 100%, and I aim to update BCD immediately after we land a new feature.

**Comment by foolip** [comment]
@lucacasonato I see, in that case I think this isn't a high priority, not much effort would be saved.

**Comment by queengooborg** [comment]
The main goal regarding this issue was to tackle NodeJS' data, which doesn't seem to have a dedicated contributor to tackle it.  I'm not as concerned about Deno, since we have an amazing contributor working hard on it.  :D If we're tackling one of the two, then the other should be fairly straightforward -- but since neither are accounted for in the real values percentage, I think this would be an in-the-future project.
