### ISSUE TITLE
Test dictionary parameters

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1485]
Mostly just filing this so I have something to point at in other issues.

We should generate tests for parameters, following the [guideline](https://github.com/mdn/browser-compat-data/blob/main/docs/data-guidelines.md#parameters-and-parameter-object-features). (See also: https://github.com/mdn/browser-compat-data/issues/7287.)

Note there's no current general purpose way to test for support of dictionary members: https://github.com/heycam/webidl/issues/107.

**Comment by foolip** [comment]
Support for this was added in https://github.com/foolip/mdn-bcd-collector/commit/b0171823a4487505016b07ab8b02d57151779c1a and `bcd.testOptionParam` is now used quite widely in https://github.com/openwebdocs/mdn-bcd-collector/blob/main/custom/tests.yaml
