### ISSUE TITLE
MediaStream tests depend on navigator.mediaDevices.getUserMedia()

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1520]
The custom tests for `MediaStream` depend on `navigator.mediaDevices.getUserMedia()`:

https://github.com/foolip/mdn-bcd-collector/blob/45c1a30614f08f7131a49bfa1d72d7b94ca81b00/custom-tests.yaml#L1195-L1199

This isn't good, because `navigator.mediaDevices.getUserMedia()` is much newer than `MediaStream`. It's especially problematic because there's a generated `if (!mediaDevices) { return false; }` in the tests, which means "definitely not supported".

This also affects `MediaStreamTrack` tests.

cc @queengooborg

**Comment by queengooborg** [comment]
We have an issue open about adding the callback-based version into the collector, see #1345.  Let me see what we can do for this!

**Comment by foolip** [comment]
Looks like I noticed the same problem in https://github.com/mdn/browser-compat-data/pull/11718#issuecomment-886199688 but didn't file an issue then.

**Comment by foolip** [comment]
Running across this again today, it's not possible to detect support for `MediaStreamTrack`'s `stop()` method correctly because of this.
