### ISSUE TITLE
Add scripts used to create BCD PRs

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1586]
@queengooborg can you add the scripts that you use to create BCD PRs?

I ask because I'd like to file an issue about the "Check out the collector's guide on how to review this PR" bit, requesting that it's *not* in the commit message and only the PR description.

**Comment by queengooborg** [comment]
The mentioned script, as well as all other scripts that I use that aren't here or in BCD, are in the following repository: https://github.com/queengooborg/bcd-toolkit/blob/main/auto-pr.sh

Unfortunately in its current state, I can't really create a separate commit message vs. PR description.
