### ISSUE TITLE
Tests get stuck on "Running tests for ServiceWorker..." in Chrome 34

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1591]
Running http://mdn-bcd-collector.appspot.com/tests/api/TextMetrics?exposure=Window in Chrome 34 on BrowserStack, it gets stuck looking like this:
![image](https://user-images.githubusercontent.com/498917/137928133-3a351805-7771-49f0-b400-57ee5336829b.png)

In the console I see this:
![image](https://user-images.githubusercontent.com/498917/137928255-82445170-6be5-4f4f-895b-b41f174c7f85.png)

I'm not sure why there's an attempt to run service worker tests at all, since there aren't any for this page.

@queengooborg have you seen this?

**Comment by queengooborg** [comment]
Hmm, I think the issue of the tests getting stuck might have been a fluke.  I've run this same test a couple of times in both BrowserStack and SauceLabs in Chrome 34 and couldn't get it to freeze.

Regarding the logs stating the tests are running in exposure sets that there aren't any tests, I'll send a PR to fix that up!
