### ISSUE TITLE
Don't render results automatically when there are lots

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1719]
I've been using the `?selenium=true` GET variable on older browsers to prevent them from rendering all of the results when running all of the tests.  Some older devices, real and emulated, simply crash if it has to render too much, others freeze up.  At first, I was thinking of just bringing back the "Hide Results" checkbox, but then I realized that means our URL will have to change, which may cause some issues.

I propose we prevent the HTML rendering of the results if there are more than, say, 100, and instead render a button and text that says something along the lines of "There are X results, do you want to render them?"

**Comment by foolip** [comment]
A button to render them all sounds good to me.
