### ISSUE TITLE
Results PRs: log the URLs from the results JSON

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1720]
Lots of random users will submit results to GitHub, some of them useful like running all the tests in a browser version we don't have, others not so much as they are just running tests for a single API.  It would be nice to get the URLs from the submitted results and log them in the commit message, so that we can quickly see what tests have been run.

**Comment by foolip** [comment]
Is the problem that you can't find your own results because of all the PRs? I regularly just close all of the PRs, does that solve the problem?

**Comment by queengooborg** [comment]
I think that some of the results PRs generated by other users can be helpful, though if it's for a small subset of tests then it's not all too helpful for us.  I want to be able to discern which results PRs would be helpful to us and which ones aren't as much.

Alternatively, we could also limit the GitHub Export button?  We could only show a GitHub export for category tests (`api`, etc.) and bigger, or perhaps only allow authorized users to submit to GitHub?  (I'm leaning towards the first one as the second one I feel would be hard to implement.)
