### ISSUE TITLE
Document only node <= 14 is supported

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1751]
Due to https://github.com/nodegit/nodegit/issues/1880, `npm ci` will fail on more recent node due to the dev dependency on nodegit.

**Comment by queengooborg** [comment]
Thanks for pointing this out.  Man, that's annoying -- it's been one problem after another with `nodegit`, but there's not really much else out there...

**Comment by gsnedders** [comment]
Given it's only used by `release.js`, does it makes sense to just bump it to an optional dependency and handle it not being available there, so you can at least install and use everything else on more recent node?

**Comment by queengooborg** [comment]
That could work, though honestly I'm considering ditching `nodegit` entirely and just sticking to piping and parsing console command output.  I'll look into this some more within the next few days!

**Comment by queengooborg** [comment]
NodeJS v14 is no longer a dependency!
