### ISSUE TITLE
c8 doesn't work with puppeteer-to-istanbul

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#1789]
Looks like there's something going on between `c8` and `puppeteer-to-istanbul`, where it's not including test results in codecov reports.

**Comment by foolip** [comment]
I think we can just drop coverage reporting of the code that's run only in the browser.

**Comment by queengooborg** [comment]
I was able to fix the issue -- turns out, since `c8` is based upon V8's internal reporting utilities, we don't need `puppeteer-to-istanbul` at all!
