### ISSUE TITLE
testCSSPropertyValue seems to give bogus results

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#1955]
At least on Safari \< 9 (i.e., when the `CSS.supports` branch isn't taken).

Dunno what's going on there, maybe only in the case when the property isn't supported? Not sure.

**Comment by foolip** [comment]
@queengooborg can you look into this?

**Comment by foolip** [comment]
I think this might be the same issue as https://github.com/openwebdocs/mdn-bcd-collector/issues/723 but am not sure.

@gsnedders if you think this is different and still relevant, can you file a new issue? The canonical repo is now https://github.com/openwebdocs/mdn-bcd-collector and I'm in the process of tombstoning this repo.
