### ISSUE TITLE
Mix of platforms leads to nonsensical results in update-bcd

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#1984]
The results for WebGL can be different on macOS and Windows. Right now, these are the reports in the results repo:

6.0.1-chrome-15.0.874.121-windows-7-dfd5407d42.json
6.0.1-chrome-16.0.912.75-mac-os-10.11.6-d4745630c1.json
6.0.1-chrome-16.0.912.77-windows-7-dad7ae650f.json
6.0.1-chrome-17.0.963.26-mac-os-10.11.6-cf03cc0e25.json
6.0.1-chrome-18.0.1025.152-windows-7-0585a19981.json
6.0.1-chrome-19.0.1084.56-windows-7-32ca0ce741.json
6.0.1-chrome-20.0.1132.47-mac-os-10.11.6-a2b47a74a2.json
6.0.1-chrome-20.0.1132.57-windows-7-697ee8a3a9.json
6.0.1-chrome-21.0.1180.57-mac-os-10.11.6-5c7846e3aa.json
6.0.1-chrome-22.0.1229.92-mac-os-10.11.6-15e879ee80.json
6.0.1-chrome-22.0.1229.96-windows-8-d2f5569ba1.json
6.0.1-chrome-23.0.1271.101-mac-os-10.11.6-06c178c556.json
6.0.1-chrome-23.0.1271.64-windows-8-e5c8b9e43e.json
6.0.1-chrome-24.0.1312.52-mac-os-10.11.6-47138aaece.json
6.0.1-chrome-24.0.1312.57-windows-8-2c8f953ce8.json
6.0.1-chrome-25.0.1364.160-windows-8-ef376feb5a.json
6.0.1-chrome-25.0.1364.172-mac-os-10.11.6-e960890490.json
6.0.1-chrome-26.0.1410.43-windows-8-b61d19a783.json
6.0.1-chrome-26.0.1410.65-mac-os-10.11.6-3004aa7e4c.json
6.0.1-chrome-27.0.1453.110-windows-8-84aeff6eee.json
6.0.1-chrome-28.0.1500.72-windows-8-ecb82877b5.json
6.0.1-chrome-29.0.1547.62-mac-os-10.14.6-da451ebef8.json
6.0.1-chrome-29.0.1547.62-windows-8-555f9585fd.json
6.0.1-chrome-30.0.1599.101-windows-8.1-bf885d0fac.json
6.0.1-chrome-31.0.1650.57-windows-8.1-7f7bb8442d.json
6.0.1-chrome-32.0.1700.102-mac-os-10.14.6-a53b862ce3.json
6.0.1-chrome-33.0.1750.117-mac-os-10.14.6-7f0c2f2ef0.json
6.0.1-chrome-35.0.1916.114-windows-8.1-c97430ac14.json
6.0.1-chrome-36.0.1985.125-windows-8.1-047c6f4e95.json
6.0.1-chrome-37.0.2062.94-mac-os-10.14.6-acbc8df285.json
6.0.1-chrome-38.0.2125.101-windows-8.1-1367e6da55.json
6.0.1-chrome-39.0.2171.65-windows-8.1-6eb7835420.json
6.0.1-chrome-40.0.2214.93-mac-os-10.16.0-6d512ff8bc.json
6.0.1-chrome-40.0.2214.93-windows-10-9a7f8af620.json
6.0.1-chrome-41.0.2272.76-mac-os-10.16.0-4bac4930e5.json
6.0.1-chrome-42.0.2311.135-mac-os-10.16.0-85f37bc6e0.json
6.0.1-chrome-43.0.2357.65-mac-os-10.16.0-0b52aa7e38.json
6.0.1-chrome-44.0.2403.89-windows-10-5bcd2c7a6e.json
6.0.1-chrome-45.0.2454.85-mac-os-10.16.0-203e1fb435.json
6.0.1-chrome-46.0.2490.71-mac-os-10.16.0-7c3fd0ee62.json
6.0.1-chrome-47.0.2526.73-mac-os-10.16.0-7709fdc3ac.json
6.0.1-chrome-48.0.2564.82-windows-10-6aa49ae3e7.json
6.0.1-chrome-49.0.2623.75-mac-os-10.16.0-587f424abc.json
6.0.1-chrome-49.0.2623.75-windows-10-c982d61747.json
6.0.1-chrome-50.0.2661.75-windows-10-bbad1517fe.json
6.0.1-chrome-51.0.2704.79-windows-10-055986fda3.json
6.0.1-chrome-52.0.2743.82-mac-os-10.16.0-bff9bd1d01.json
6.0.1-chrome-53.0.2785.89-mac-os-10.16.0-4b4bb6932c.json
6.0.1-chrome-54.0.2840.59-windows-10-72b04af550.json
6.0.1-chrome-55.0.2883.75-mac-os-10.16.0-9b3132639a.json
6.0.1-chrome-55.0.2883.75-windows-10-7ae1ffe47b.json
6.0.1-chrome-56.0.2924.76-mac-os-10.16.0-17e371b8e6.json
6.0.1-chrome-57.0.2987.110-windows-10-35d119e721.json
6.0.1-chrome-58.0.3029.81-mac-os-10.16.0-fbd0eb21ec.json
6.0.1-chrome-58.0.3029.81-windows-10-9a37ae3d24.json
6.0.1-chrome-59.0.3071.86-mac-os-10.16.0-971fb60395.json
6.0.1-chrome-59.0.3071.86-windows-10-c83d7c0aa3.json
6.0.1-chrome-60.0.3112.78-windows-10-cf9b072527.json
6.0.1-chrome-61.0.3163.79-mac-os-10.16.0-ad27824daa.json
6.0.1-chrome-61.0.3163.91-windows-10-8d567a4d5a.json
6.0.1-chrome-62.0.3202.62-mac-os-10.16.0-9d3f401733.json
6.0.1-chrome-62.0.3202.62-windows-10-800dbafef0.json
6.0.1-chrome-63.0.3239.132-mac-os-10.16.0-561bc5aafc.json
6.0.1-chrome-63.0.3239.132-windows-10-e66dcb6667.json
6.0.1-chrome-64.0.3282.119-windows-10-4bd6600c4e.json
6.0.1-chrome-65.0.3325.146-mac-os-10.16.0-252a618aa1.json
6.0.1-chrome-65.0.3325.181-windows-10-d35cb18be2.json
6.0.1-chrome-66.0.3359.117-mac-os-10.16.0-21a9128c8f.json
6.0.1-chrome-66.0.3359.170-windows-10-af1fe5f98d.json
6.0.1-chrome-67.0.3396.62-mac-os-10.16.0-b484975ef3.json
6.0.1-chrome-67.0.3396.62-windows-10-2960ae5539.json
6.0.1-chrome-68.0.3440.84-windows-10-c9e8a00a01.json
6.0.1-chrome-69.0.3497.81-mac-os-10.16.0-a3f5bc1ec8.json
6.0.1-chrome-69.0.3497.92-windows-10-82b75eccae.json
6.0.1-chrome-70.0.3538.67-mac-os-10.16.0-e439eb0aad.json
6.0.1-chrome-70.0.3538.67-windows-10-81366b59e5.json
6.0.1-chrome-71.0.3578.30-windows-10-868038f22e.json
6.0.1-chrome-71.0.3578.80-mac-os-10.16.0-afa1d0bafc.json
6.0.1-chrome-72.0.3626.109-windows-10-0ee27aa4b5.json
6.0.1-chrome-72.0.3626.119-mac-os-10.16.0-3c265d2601.json
6.0.1-chrome-73.0.3683.46-windows-10-534f81e6e8.json
6.0.1-chrome-73.0.3683.75-mac-os-10.16.0-1b826803ea.json
6.0.1-chrome-74.0.3729.131-windows-10-74cc246201.json
6.0.1-chrome-74.0.3729.169-mac-os-10.16.0-64a3ab0393.json
6.0.1-chrome-75.0.3770.100-mac-os-10.16.0-8d2f391ec9.json
6.0.1-chrome-75.0.3770.80-windows-10-bbdec934f1.json
6.0.1-chrome-76.0.3809.87-mac-os-10.16.0-2f5e03329b.json
6.0.1-chrome-76.0.3809.87-windows-10-e4fc6fec8b.json
6.0.1-chrome-77.0.3865.75-windows-10-027fe18fe8.json
6.0.1-chrome-77.0.3865.90-mac-os-10.16.0-2b76a5f4ac.json
6.0.1-chrome-78.0.3904.108-mac-os-10.16.0-2293ad862e.json
6.0.1-chrome-78.0.3904.70-mac-os-10.16.0-283df1b198.json
6.0.1-chrome-78.0.3904.70-windows-10-f65a2e485f.json
6.0.1-chrome-79.0.3945.16-windows-10-f6398123fb.json
6.0.1-chrome-79.0.3945.88-mac-os-10.16.0-4458a2b65a.json
6.0.1-chrome-80.0.3987.132-windows-10-f09de14bde.json
6.0.1-chrome-80.0.3987.87-mac-os-10.16.0-56c224aa2c.json
6.0.1-chrome-81.0.4044.129-mac-os-10.16.0-1a67763b99.json
6.0.1-chrome-81.0.4044.129-windows-10-2070322e2c.json
6.0.1-chrome-83.0.4103.61-mac-os-10.16.0-866ee7c0e7.json
6.0.1-chrome-83.0.4103.61-windows-10-8f883a46d0.json
6.0.1-chrome-84.0.4147.89-mac-os-10.14.0-af1f1725c7.json
6.0.1-chrome-84.0.4147.89-windows-10-f1bb5078ed.json
6.0.1-chrome-85.0.4183.83-mac-os-10.16.0-ec2c54a343.json
6.0.1-chrome-85.0.4183.83-windows-10-cb80dd4997.json
6.0.1-chrome-86.0.4240.183-mac-os-11.0.0-c460632e1a.json
6.0.1-chrome-86.0.4240.183-windows-10-55a50e18d6.json
6.0.1-chrome-87.0.4280.66-windows-10-5b8b80fe64.json
6.0.1-chrome-87.0.4280.67-mac-os-11.0.0-ad1a5ba7dd.json
6.0.1-chrome-88.0.4324.150-windows-10-379269f3a3.json
6.0.1-chrome-88.0.4324.96-mac-os-12.0.1-9ec209ebc2.json
6.0.1-chrome-89.0.4389.82-mac-os-12.0.1-6db1b6d07b.json
6.0.1-chrome-89.0.4389.90-windows-10-49fc34073f.json
6.0.1-chrome-90.0.4430.72-windows-10-b383bec8d9.json
6.0.1-chrome-90.0.4430.93-mac-os-10.15.7-0b6a40a327.json
6.0.1-chrome-91.0.4472.106-windows-10-e9abd6c5a8.json
6.0.1-chrome-91.0.4472.77-mac-os-10.14.0-9992a53613.json
6.0.1-chrome-92.0.4515.107-mac-os-10.15.7-21fec29002.json
6.0.1-chrome-92.0.4515.107-windows-10-262a33046b.json
6.0.1-chrome-93.0.4577.63-mac-os-10.15.7-6a503ac21d.json
6.0.1-chrome-93.0.4577.63-windows-10-8b4c44c982.json
6.0.1-chrome-94.0.4606.71-mac-os-10.15.7-c822659744.json
6.0.1-chrome-94.0.4606.81-windows-10-e5b46d9dee.json
6.0.1-chrome-95.0.4638.54-mac-os-10.15.7-f9ecc3ef97.json
6.0.1-chrome-95.0.4638.54-windows-10-2d31f2cb1e.json
6.0.1-chrome-96.0.4664.27-windows-10-d37eb5246b.json
6.0.1-chrome-96.0.4664.45-mac-os-10.14.0-6aaf37dd26.json
6.0.1-chrome-97.0.4692.71-mac-os-10.15.7-381b723edb.json
6.0.1-chrome-97.0.4692.71-windows-10-2160a0ed7b.json
6.0.1-chrome-98.0.4758.54-windows-10-35d35bef50.json
6.0.1-chrome-98.0.4758.80-mac-os-10.14.0-f7fafd7d45.json
6.0.1-chrome-99.0.4844.51-mac-os-10.15.7-a2231d3ff7.json
6.0.1-chrome-99.0.4844.51-windows-10-9b05fee85b.json
6.0.1-chrome-100.0.4896.60-windows-10-1b418f28d9.json
6.0.1-chrome-100.0.4896.75-mac-os-10.15.7-14c01cc999.json

It's a mix of macOS-only, Windows-only and both for different versions of Chrome. Due to the platform-specific results, this leads to this inferred support in the update-bcd script, when running `npm run update-bcd -- --browser=chrome --path=api.WebGLRenderingContext.lineWidth`:

```js
[
  { version_added: '16', version_removed: '18' },
  { version_added: '20', version_removed: '48' },
  { version_added: '49', version_removed: '52' },
  { version_added: '53', version_removed: '56' },
  { version_added: '57' }
]
```

@queengooborg is this a result of the Selenium script using whichever platform is available?

**Comment by gsnedders** [comment]
> The results for WebGL can be different on macOS and Windows.

And between different hardware, too, given what ANGLE exposes differs: https://github.com/google/angle/blob/main/doc/ExtensionSupport.md

**Comment by gsnedders** [comment]
see also: #571
