### ISSUE TITLE
Invalid test for `list-style-type` CSS property values

### ISSUE THREAD

**Issue by jugglinmike** [foolip/mdn-bcd-collector#2347]
[The "harness" test for CSS property values](https://github.com/foolip/mdn-bcd-collector/blob/7c64b96cc79beb4576e4f5daf6669a67b3d478ef/static/resources/harness.js#L286-L295) uses the `CSS.supports` function where available. This is not a reliable way to test support for `list-style-type` values because [that CSS property accepts any arbitrary string value](https://w3c.github.io/csswg-drafts/css-lists-3/#text-markers).

This is apparent in the data for Chrome stored in [the mdn-bcd-results repository](https://github.com/foolip/mdn-bcd-results): the results for the value `"afar"` are `true` for versions 1 through 44, `false` for versions 45 through 90, and then `true` again for versions 91 through 105.

<details>
  <summary>click to reveal an awful shell script which highlights the relevant results</summary>

    $ for f in *chrome*mac-os*; do v=$(echo $f | sed 's/^.*chrome-\([^-]\+\)-.*$/\1/g'); r=$(python -m json.tool < $f | grep -A1 '\.afar' | tail -n1); echo $v $r; done | sort -n
    16.0.912.75 "result": true
    17.0.963.26 "result": true
    18.0.1025.151 "result": true
    19.0.1084.56 "result": true
    20.0.1132.47 "result": true
    21.0.1180.57 "result": true
    22.0.1229.92 "result": true
    23.0.1271.101 "result": true
    24.0.1312.52 "result": true
    25.0.1364.172 "result": true
    26.0.1410.65 "result": true
    27.0.1453.116 "result": true
    29.0.1547.62 "result": true
    30.0.1599.101 "result": true
    31.0.1650.57 "result": true
    32.0.1700.102 "result": true
    33.0.1750.117 "result": true
    35.0.1916.114 "result": true
    37.0.2062.94 "result": true
    38.0.2125.101 "result": true
    40.0.2214.93 "result": true
    41.0.2272.76 "result": true
    42.0.2311.135 "result": true
    43.0.2357.65 "result": true
    44.0.2403.89 "result": true
    45.0.2454.85 "result": false
    46.0.2490.71 "result": false
    47.0.2526.73 "result": false
    48.0.2564.97 "result": false
    49.0.2623.75 "result": false
    50.0.2661.75 "result": false
    51.0.2704.79 "result": false
    52.0.2743.82 "result": false
    53.0.2785.89 "result": false
    54.0.2840.59 "result": false
    55.0.2883.75 "result": false
    56.0.2924.76 "result": false
    57.0.2987.98 "result": false
    58.0.3029.81 "result": false
    59.0.3071.86 "result": false
    60.0.3112.78 "result": false
    61.0.3163.79 "result": false
    62.0.3202.62 "result": false
    63.0.3239.84 "result": false
    65.0.3325.146 "result": false
    66.0.3359.117 "result": false
    67.0.3396.62 "result": false
    68.0.3440.75 "result": false
    69.0.3497.81 "result": false
    70.0.3538.67 "result": false
    71.0.3578.80 "result": false
    72.0.3626.81 "result": false
    73.0.3683.75 "result": false
    74.0.3729.131 "result": false
    75.0.3770.80 "result": false
    76.0.3809.87 "result": false
    77.0.3865.75 "result": false
    78.0.3904.70 "result": false
    79.0.3945.79 "result": false
    80.0.3987.132 "result": false
    81.0.4044.129 "result": false
    83.0.4103.61 "result": false
    84.0.4147.89 "result": false
    85.0.4183.83 "result": false
    86.0.4240.183 "result": false
    87.0.4280.66 "result": false
    88.0.4324.150 "result": false
    89.0.4389.90 "result": false
    90.0.4430.72 "result": false
    91.0.4472.106 "result": true
    92.0.4515.107 "result": true
    93.0.4577.63 "result": true
    94.0.4606.71 "result": true
    95.0.4638.54 "result": true
    96.0.4664.110 "result": true
    97.0.4692.71 "result": true
    98.0.4758.80 "result": true
    99.0.4844.51 "result": true
    100.0.4896.127 "result": true
    101.0.4951.41 "result": true
    102.0.5005.61 "result": true
    103.0.5060.114 "result": true
    104.0.5112.79 "result": true
    105.0.0.0 "result": true

</details>

The `update-bcd` script does not reflect this history in BCD due to [a known deficiency](https://github.com/foolip/mdn-bcd-collector/blob/7c64b96cc79beb4576e4f5daf6669a67b3d478ef/update-bcd.ts#L315).

**Comment by foolip** [comment]
Hmm, I wonder if this affects other properties as well? I suppose we could test a known unsupported value for all properties and look into the ones that are "supported".

**Comment by foolip** [comment]
Reposted at https://github.com/openwebdocs/mdn-bcd-collector/issues/723.
