### ISSUE TITLE
Invalid test for `transition` CSS property value

### ISSUE THREAD

**Issue by jugglinmike** [foolip/mdn-bcd-collector#2384]
[BCD includes support data for a feature of the `transition` CSS property which is simply referred to as "Gradients."](https://github.com/mdn/browser-compat-data/blob/a7f717525bb6b8fced21ac4e468a345051cca577/css/properties/transition.json#L112-L147) I can't find any explanation for what this means (neither on [the MDN page](https://developer.mozilla.org/en-US/docs/Web/CSS/transition) nor in [the relevant specification](https://w3c.github.io/csswg-drafts/css-transitions-1/#single-transition-property)), though. In the absence of any evidence of a feature specific to the `transition` property itself, my guess is that this is intended to describe support for transitioning the `background-image` property when it takes a CSS gradient value.

However, that is not what the generated test attempts to verify. Instead, it checks if the `transition` property accepts the value `gradients`:

    $ python -m json.tool < tests.json | grep '\.transition\.gradients' -A5
        "css.properties.transition.gradients": {
            "code": "bcd.testCSSPropertyValue(\"transition\", \"gradients\")",
            "exposure": [
                "Window"
            ]
        },

This looks like a mistake to me. As written, the test passes consistently in all releases of Chrome and Firefox, in contradiction to the data in BCD. According to my reading of the spec, that's because the property can take any value.

<details>
  <summary>here are the passing results from mdn-bcd-results for Firefox versions 16 through 104</summary>

    $ for f in *firefox*mac-os*; do v=$(echo $f | sed 's/^.*chrome-\([^-]\+\)-.*$/\1/g'); r=$(python -m json.tool < $f | grep -A1 '\.transition\.gradients' | tail -n1); echo $v $r; done | sort -n
    6.2.2-firefox-100.0-mac-os-10.15-3ef0647e87.json "result": true
    6.2.2-firefox-101.0-mac-os-10.15-a59c2de0ed.json "result": true
    6.2.2-firefox-102.0-mac-os-10.15-1ea2bfefb5.json "result": true
    6.2.2-firefox-103.0-mac-os-10.15-9a827942d9.json "result": true
    6.2.2-firefox-104.0-mac-os-10.15-7aeda85c19.json "result": true
    6.2.2-firefox-16.0-mac-os-10.16-e5d46b8889.json "result": true
    6.2.2-firefox-17.0-mac-os-10.16-19809b7efc.json "result": true
    6.2.2-firefox-18.0-mac-os-10.16-b41d85a3ea.json "result": true
    6.2.2-firefox-19.0-mac-os-10.16-8b9d3f7d0c.json "result": true
    6.2.2-firefox-20.0-mac-os-10.16-54a6c0757f.json "result": true
    6.2.2-firefox-21.0-mac-os-10.16-fa0da0a6ee.json "result": true
    6.2.2-firefox-22.0-mac-os-10.16-f90960fc25.json "result": true
    6.2.2-firefox-23.0-mac-os-10.16-d803358f83.json "result": true
    6.2.2-firefox-24.0-mac-os-10.16-b34417e482.json "result": true
    6.2.2-firefox-25.0-mac-os-10.16-9bf8c6ce7d.json "result": true
    6.2.2-firefox-26.0-mac-os-10.16-68da896697.json "result": true
    6.2.2-firefox-27.0-mac-os-10.16-8a85aafff7.json "result": true
    6.2.2-firefox-28.0-mac-os-10.16-6c0398960d.json "result": true
    6.2.2-firefox-29.0-mac-os-10.16-57d6be3b97.json "result": true
    6.2.2-firefox-30.0-mac-os-10.16-e06123965f.json "result": true
    6.2.2-firefox-31.0-mac-os-10.16-150c16ad94.json "result": true
    6.2.2-firefox-32.0-mac-os-10.16-110336a414.json "result": true
    6.2.2-firefox-33.0-mac-os-10.16-1dcf0edb65.json "result": true
    6.2.2-firefox-34.0-mac-os-10.16-ff1c81d398.json "result": true
    6.2.2-firefox-35.0-mac-os-10.16-01f1676a21.json "result": true
    6.2.2-firefox-36.0-mac-os-10.0-09d4125d6d.json "result": true
    6.2.2-firefox-37.0-mac-os-10.0-9fec0aaf88.json "result": true
    6.2.2-firefox-47.0-mac-os-10.0-3f16153c26.json "result": true
    6.2.2-firefox-48.0-mac-os-10.0-4e53c408ca.json "result": true
    6.2.2-firefox-49.0-mac-os-10.0-ee46f714b9.json "result": true
    6.2.2-firefox-50.0-mac-os-10.0-be5ca01520.json "result": true
    6.2.2-firefox-51.0-mac-os-10.0-b85906438e.json "result": true
    6.2.2-firefox-53.0-mac-os-10.0-928434eda9.json "result": true
    6.2.2-firefox-54.0-mac-os-10.0-76e5fddef3.json "result": true
    6.2.2-firefox-55.0-mac-os-10.0-1d5bc05563.json "result": true
    6.2.2-firefox-56.0-mac-os-10.0-6170b0fd52.json "result": true
    6.2.2-firefox-57.0-mac-os-10.0-753257a84e.json "result": true
    6.2.2-firefox-58.0-mac-os-10.0-3d8b340b38.json "result": true
    6.2.2-firefox-59.0-mac-os-10.0-a86bc60e2e.json "result": true
    6.2.2-firefox-61.0-mac-os-10.0-4827f3e7e6.json "result": true
    6.2.2-firefox-62.0-mac-os-10.0-49671f46e9.json "result": true
    6.2.2-firefox-63.0-mac-os-10.0-7b1b568800.json "result": true
    6.2.2-firefox-64.0-mac-os-10.0-66f0ae7c09.json "result": true
    6.2.2-firefox-65.0-mac-os-10.0-e096208173.json "result": true
    6.2.2-firefox-66.0-mac-os-10.0-c47100b32d.json "result": true
    6.2.2-firefox-67.0-mac-os-10.0-094efac358.json "result": true
    6.2.2-firefox-68.0-mac-os-10.0-7502ca707a.json "result": true
    6.2.2-firefox-69.0-mac-os-10.0-7d6c606c9f.json "result": true
    6.2.2-firefox-70.0-mac-os-10.0-1b006e7c0b.json "result": true
    6.2.2-firefox-71.0-mac-os-10.0-b5bb5c7368.json "result": true 
    6.2.2-firefox-72.0-mac-os-10.0-ff969898d7.json "result": true 
    6.2.2-firefox-73.0-mac-os-10.0-557bfb4004.json "result": true 
    6.2.2-firefox-74.0-mac-os-10.0-24f2481598.json "result": true 
    6.2.2-firefox-75.0-mac-os-10.0-b65ddef5f0.json "result": true 
    6.2.2-firefox-76.0-mac-os-10.0-9ff7d02bfb.json "result": true
    6.2.2-firefox-77.0-mac-os-10.0-80e6fa909f.json "result": true
    6.2.2-firefox-78.0-mac-os-10.16-9d405acc1f.json "result": true
    6.2.2-firefox-79.0-mac-os-10.16-cc7978e10d.json "result": true
    6.2.2-firefox-80.0-mac-os-10.16-b6b3c7f186.json "result": true
    6.2.2-firefox-81.0-mac-os-10.16-4ef7995d6b.json "result": true
    6.2.2-firefox-82.0-mac-os-10.16-d82b546362.json "result": true
    6.2.2-firefox-83.0-mac-os-10.16-df31f262af.json "result": true
    6.2.2-firefox-84.0-mac-os-10.16-cfb1cacb13.json "result": true
    6.2.2-firefox-85.0-mac-os-10.16-d4015e7363.json "result": true
    6.2.2-firefox-86.0-mac-os-10.16-f4d2e10874.json "result": true
    6.2.2-firefox-87.0-mac-os-10.15-81c66b4814.json "result": true
    6.2.2-firefox-88.0-mac-os-10.15-96c52194aa.json "result": true
    6.2.2-firefox-89.0-mac-os-10.15-df8fe07131.json "result": true
    6.2.2-firefox-90.0-mac-os-10.15-d9504c07fc.json "result": true
    6.2.2-firefox-92.0-mac-os-10.15-9861b18ba7.json "result": true
    6.2.2-firefox-93.0-mac-os-10.15-d1cbb7a86f.json "result": true
    6.2.2-firefox-94.0-mac-os-10.15-d698a4f931.json "result": true
    6.2.2-firefox-95.0-mac-os-10.15-726881eed4.json "result": true
    6.2.2-firefox-96.0-mac-os-10.15-82c6e22d8a.json "result": true
    6.2.2-firefox-97.0-mac-os-10.15-5144d24c95.json "result": true
    6.2.2-firefox-98.0-mac-os-10.15-952749cda7.json "result": true
    6.2.2-firefox-99.0-mac-os-10.15-cff9a43685.json "result": true

</details>

This seems similar to gh-2347, but unlike `list-style-type`, it's not clear what value, if any, is being tested.

**Comment by foolip** [comment]
This was fixed in https://github.com/openwebdocs/mdn-bcd-collector/commit/75e3f1221ffc68f6f7c4eb7a343a34a3074eae1e.
