### ISSUE TITLE
Unqualified "TODO" code comment

### ISSUE THREAD

**Issue by jugglinmike** [foolip/mdn-bcd-collector#2805]
The `update-bcd.ts` script has eight "TODO"-style code comments, but one of them omits an explanation of the task which motivated it:

https://github.com/foolip/mdn-bcd-collector/blob/723b755a1f8717b3e9088778ca954574686856d7/update-bcd.ts#L290-L295

The comment introduced in 2020 via commit d5ff5fe2. Its position implies that something more ought to be done when encountering a browser version with no support information, but I haven't been able to infer what that is.

I've been gathering together a list of enhancements for that script, and I don't want to miss whatever functionality motivated that comment.

**Comment by foolip** [comment]
@queengooborg can you speak to this?

**Comment by foolip** [comment]
Closing this issue to tombstone this repo. @jugglinmike since the update script has now moved to BCD in https://github.com/mdn/browser-compat-data/pull/19971, can you refile the issue on BCD if you feel it is still relevant?
