### ISSUE TITLE
Handle conflicting results?

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#375]
As the results repo grows larger and larger, there's going to be a high probability of conflicts in the data for numerous reasons -- such as different exposure times in different scopes, adjustments to the tests, different implementation for different OSes, and sometimes, even patch versions of browsers (implemented in Chrome 54.0.2835 and removed in Chrome 54.0.2836).  We will need to implement conflict-processing.

What I'm thinking is the following conflict handling (in order of preference):
- Prefer higher collector version -- if the results from `mdn-bcd-collector` 0.0.5 and 0.0.6 differ, choose results from 0.0.6 (test could have been patched)
- Prefer higher patch version of browser -- if the results from Chrome 84.0.4147.89 and 84.0.4147.135 differ, choose results from 84.0.4147.135
- Prefer "true" result if different OSes -- if the results from macOS says "true" but Ubuntu Linux says "false", the result is "true"
- Prefer higher OS version -- if tests from macOS 10.14 and 10.15 have conflicting results, choose results from 10.15
- Prefer the more likely answer -- if two results files for the same version say "true" but one says "false", say "true" (in the case of 50/50 results, say "null" since we can't determine)

Of course, there will be other issues along the way -- a good example is people modifying their user agents -- but we can figure those out later.

_Issue inspired by https://github.com/mdittmer/mdn-confluence/pull/47._

**Comment by foolip** [comment]
I think that sounds like the right rules. What I found in https://github.com/mdittmer/mdn-confluence/pull/47 was mostly the same browser version of different OSes or different versions of the same OS giving different results. For the latter, we should prefer the most recent version of the OS, as it might be a feature that's conditionally enabled based on OS support. For things that are different between for example macOS and Windows for the same browser, notes are the only way of representing that.

**Comment by vinyldarkscratch** [comment]
Added two list entries for the OS differences!

**Comment by foolip** [comment]
Hijacking this issue to remember sorting out https://github.com/foolip/mdn-bcd-collector/pull/416/files#r485522138. That's a case of conflicting results :)
