### ISSUE TITLE
Expose URLs for the individual tests

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#376]
When updating BCD based on the results, one will often want to verify using BrowserStack or Sauce Labs, especially if the proposed change seems implausible.

Currently, what I do is write a new test by hand in https://software.hixie.ch/utilities/js/live-dom-viewer/ and try that in different browsers. This is very time consuming.

I think we should have URLs for each individual test, or at least each individual BCD path. PRs on BCD should then link to these tests, so the URLs should be stable.

I have this approach in mind:
- Move test generation to the server at runtime, instead of in a build step.
- A URL like `/api/` might include all tests for api.*, while `/tests/api/HTMLMediaElement/audioTracks` would include the tests for `api.HTMLMediaElement.audioTracks`.
- When visiting one of these pages manually, the results are shown visually.
- Still have a default grouping and no visual results for automated collection.

@vinyldarkscratch WDYT?

**Comment by foolip** [comment]
The "Move test generation to the server at runtime" bit could be softened to just generating a database of available tests and letting the server assemble those into responses. It's very convenient to have the full output of such a step available for diffing to see what impact a change is going to have.

**Comment by vinyldarkscratch** [comment]
I like the idea of having URLs for individual tests so they can be run individually and manually, so that anyone can use the tests provided, and suggest changes if needed.  I think that a URL would make the most sense!  I think that `/tests/api/HTMLMediaElement/audioTracks` would also display the results right there, rather than send the results to the server, perhaps?

(Regarding the visualization, I was actually thinking of providing more verbosity (and add some additional UI stuff like a spinner) to tell the user that tests are happening and the page isn't frozen, for example.)

**Comment by foolip** [comment]
Sounds like we're on the same page.

One minor point though. If there is any feedback while the tests are running, then it's important that the scripts involved use as archaic JavaScript as possible, and don't add any global variables or modify the DOM in any non-trivial way.

Ideally the test code runs first, so that the test code can have full control over the DOM and the scripting environment. Once completed it's fine to pull in more CSS and JavaScript to display the results. So anything that happens before the tests have run needs to be fairly minimal. Updating `document.title` or a single `<pre>Running test 3/5</pre>` would be OK I think.

**Comment by foolip** [comment]
https://github.com/foolip/mdn-bcd-collector/pull/398, cool!

Reopening to file a bug report: http://mdn-bcd-collector.appspot.com/ has a dropdown, but no items in the dropdown. So I can't test if this works well or not :)

**Comment by vinyldarkscratch** [comment]
What browser and what browser version are you checking it out with?

**Comment by foolip** [comment]
I was using Chrome 85 on macOS. I see it works in Firefox and Safari, but the dropdown opens very slowly.

**Comment by foolip** [comment]
I looked at the build output to figure out what the URLs were. I've tried http://mdn-bcd-collector.appspot.com/api/Range/expand.html and have some feedback.

First, a nit on the URL structure. Because api.Range.expand could have subfeatures in BCD with custom tests in the collector, I think that /api/Range/expand/ would be better, which would run all tests for the features and any subfeatures.

Generalizing that, I would like /api/Range/ to run all tests for the Range interface. That will sometimes be more useful when stepping between versions, to see which things change together.

For CSS properties, there should be multiple tests for the property itself, but http://mdn-bcd-collector.appspot.com/css/properties/border-image.html has only one. There should also be a test using `CSS.supports`, like /css/properties/dot-supports.html.

Finally, I think it would be great if view source showed what the test is, if there was as little indirection as possible that can break in ancient browsers, or that people need to understand to trust the results.

I think this points in this direction:
- Generate a database (JSON file) of tests per BCD data path.
- Let the server use that database to generate the test pages, keeping the output of those pages as trivial as possible. The browser should not need to query an interpret MANIFEST.json to run tests.

**Comment by vinyldarkscratch** [comment]
#399 should fix some of the issues with the URL generation and the CSS test generation!  Having more server-side test generation also sounds like a good idea in general -- I'll get started on something soon.

**Comment by foolip** [comment]
I still can't get the dropdown to show. I think there might be too many entries and that makes it slow to the point of seeming broken, but I'm not sure.

**Comment by vinyldarkscratch** [comment]
Perhaps, due to the size of the dropdown, we should divert to some other UI.  Either that, or bring in a dependency to make it a dropdown-search combo, like "Select2".  What do you think?

**Comment by foolip** [comment]
I would probably try a `<datalist>` first, to see if that works with a lot of options. It makes it easier to search among the options, which is a huge plus.

**Comment by vinyldarkscratch** [comment]
The `<datalist>` does seem to work with lots of options, though it's also a bit laggy.  It appears to be a better option, however!

**Comment by vinyldarkscratch** [comment]
Looking deeper into `<datalist>`, it appears there's a few issues, especially with cross-browser support.  Chrome, Firefox, and Safari each handle the display of entries differently -- Firefox only displays the text, while Safari only displays the value (and seems to cut it off too), though Chrome displays both but cuts the length.  It seems that with `<datalist>`, it allows for input other than what's in the list, requiring some JavaScript to validate options.  It's certainly quite laggy when typing input too...

**Comment by foolip** [comment]
If it's too demanding on the front end, then we could perhaps have an API for completing a search string on the backend, which will have the complete list of tests loaded into memory at all times.

**Comment by foolip** [comment]
This is done now. Examples:
https://mdn-bcd-collector.appspot.com/tests/api/TextTrackList/getTrackById
https://mdn-bcd-collector.appspot.com/tests/css/properties/-webkit-mask-repeat-x

Thanks @vinyldarkscratch!
