### ISSUE TITLE
update-bcd: treats "null" for all versions as "false"

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#377]
If all of the results say "null", the update script returns "false" as the data.  This is inaccurate; we should return "null" instead.

**Comment by foolip** [comment]
These results are inconclusive, and we should treat them the same as having no results at all. The error messages might give clues to a human, though.

Given a series of results like this:
<table>
<tr><th>Browser version<th>Test result</tr>
<tr><td>10<td>false
<tr><td>10<td>false
<tr><td>10<td>false
<tr><td>10<td>false
<tr><td>10<td>false
</table>

**Comment by vinyldarkscratch** [comment]
Looks like this has now been resolved as shown in the unittests, so we can safely close this!
