### ISSUE TITLE
Prefix testing: move prefix tests to build and test all prefixes

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#387]
Currently, prefixes are generated in `harness.js` and are tested for the first supported prefix (being none to begin).  However, this means we cannot determine when the prefix support was removed.  Instead, we should generate all of the prefixes in `build.js` and test them all.

**Comment by foolip** [comment]
Generating all possible prefixed APIs is going to increase the number of tests by a lot. One approach I've considered in the past is to test for the variants that are already in BCD, by looking at `alternative_name` and `prefix`.

**Comment by vinyldarkscratch** [comment]
That's a good point, especially since our tests are already fairly large...
