### ISSUE TITLE
Interface member tests should be inconclusive if the interface object is not exposed

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#406]
http://mdn-bcd-collector.appspot.com/api/Element/getAttribute/ has a generated test `"Element" in self && "getAttribute" in Element.prototype`. That should be just `"getAttribute" in Element.prototype` so that it throws an exception if Element was not exposed. The result should be null,  not false.

The reason for this is that if the interface object isn't exposed, we can't be sure that the member isn't. The interface might still be supported, just not exposed, or exposed under an alias which is already in the data.

**Comment by vinyldarkscratch** [comment]
Actually, I had made that change intentionally to produce `false` if the interface isn't exposed normally.  This lets us write more data in BCD as `false` if the interface is not implemented, allowing us to fix consistency issues.  If the interface isn't exposed normally and instead is accessible through other ways, that's where we should be writing a custom test.

**Comment by foolip** [comment]
My concern is that this will cause us to suggest updates in BCD that are wrong because the interface object is missing. https://chromium.googlesource.com/chromium/src/+/b7e3a7693e9f76ecedf3c78e9484463259d7f4b8 is a typical example of a feature history that would be problematic. The `RTCDTMFSender` interface object wasn't exposed for a long time, but it was implemented. By testing for the interface, we would suggest a lot of changes to subfeatures of https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender. From the fact that the interface object has gone from not exposed to exposed, I think at most we should revisit if the main feature has the right version in BCD. BCD lints would catch if one forgets to also update the subfeatures.

One could of course handle this in update-bcd.js and make the updating of subfeatures depend on the outcome of the status of the main feature. However, if the end result is the same, I'd favor the simplicity of shorter tests and making it explicit that the outcome of the test was inconclusive because the interface object is missing.

**Comment by foolip** [comment]
Is this something we can resolve sooner rather than later? When reviewing https://github.com/mdn/browser-compat-data/pull/6642, my confidence in any change that changes an interface member to false is not high, because it might be a side effect of this issue. Even when it's been verified manually, if the manual testing made the same assumptions, then the main point of review is to consider if the interface itself has been exposed under a different name, or had `[NoInterfaceObject]` at some point.

By treating these differently, review will be faster overall, because cases where the interface object and some members exist, but others do not, are ones where one can be highly confident in the change and need not spend much time probing the history of the feature.

**Comment by foolip** [comment]
@vinyldarkscratch this is fixed now, right?

**Comment by vinyldarkscratch** [comment]
Yep, this is fixed now!

**Comment by swanprincess386** [comment]
> http://mdn-bcd-collector.appspot.com/api/Element/getAttribute/ has a generated test `"Element" in self && "getAttribute" in Element.prototype`. That should be just `"getAttribute" in Element.prototype` so that it throws an exception if Element was not exposed. The result should be null, not false.
> 
> The reason for this is that if the interface object isn't exposed, we can't be sure that the member isn't. The interface might still be supported, just not exposed, or exposed under an alias which is already in the data.
