### ISSUE TITLE
Generate test database vs. HTML files

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#413]
To aid in tests, we should do the following (as suggested in https://github.com/foolip/mdn-bcd-collector/issues/376#issuecomment-685021436):

- Generate a database (JSON file) of tests per BCD data path.
- Let the server use that database to generate the test pages, keeping the output of those pages as trivial as possible. The browser should not need to query and interpret MANIFEST.json to run tests.

**Comment by foolip** [comment]
That's what I had in mind. What do you think, is there another approach that would get the job done equally well?

**Comment by vinyldarkscratch** [comment]
I think that makes the most sense, yeah. The least client side code there is, the better, I say.

Let's see… How do we want to structure this database? I'm thinking two separate members in the database; one with a mapping of URLs to identifiers, and another for￼ identifiers to tests?￼

**Comment by vinyldarkscratch** [comment]
I'm now working on something for this, which can be seen in the [`server-side-builds`](https://github.com/foolip/mdn-bcd-collector/tree/server-side-builds) branch.  (At the time of this writing, it has only updated the build script, and not the rest of the system, which will be coming up soon.)

**Comment by vinyldarkscratch** [comment]
I've gotten a lot of work done towards this, I'm happy to say!  I have reworked the `manifest.json` file into a database as proposed above, and have moved a majority of code server-side once again.  I've made sure that the endpoints function as expected as well!

**Comment by foolip** [comment]
That's exciting, thank you! My work week is over so I can't promise to get it reviewed until next week, but I would encourage you to experiment with it and shake out as many issues as you can in the meantime. If deploying live is the quickest way to do that, that'd be fine.

We could also arrange to deploy staging instances from certain branches, if that would help.
