### ISSUE TITLE
Move backend endpoints?

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#414]
The `/api/` URL contains two separate pieces of functionality in it -- the API tests, and the API endpoints.  We should rename the API endpoint URLs to something else (for example, `/backend/` or just leave them as-is).  Either that, or move the tests themselves to a new URL, which we could do considering #413.

**Comment by foolip** [comment]
Putting the tests in /test/ or /tests/ makes all URLs longer and I expect to fairly often type them out manually when I can guess the URL, but I still think that's the URL structure that's the easiest to guarantee will be stable over time. So I'd lean towards doing just that, and keeping /api/ for the other stuff we have there.

**Comment by vinyldarkscratch** [comment]
Okay, sounds good to me!  I'll place all the tests under `/tests/`.  (I'll also throw the Mocha tests into `/unittest/`).
