### ISSUE TITLE
Keep/remove Prettier?

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#415]
In the 0.0.2 release, I added Prettier as a dependency for code formatting.  However, after some further research, I realized that Google already has code formatting rules added into ESLint.  I'm wondering, should we keep it around, or would it be better to remove it?  If we keep it, we'd have a more dedicated formatting plugin which supports auto-formatting in most modern editors, though we'd have to tweak things up a bit to make it follow the Google styling.  If we remove it, it'll be one less dependency and we can use the existing code styling rules in ESLint, but ESLint isn't really meant to be used for code formatting (and editors don't auto-fix ESLint issues).

**Comment by foolip** [comment]
I don't have a wrong preference, but on some other projects I use only eslint with the Google style and it does reformat code just fine. Fewer dependencies are always nice, but Prettier has no dependencies in turn so it's not a big problem.

If you also have no preference, then I'd say use eslint only.

**Comment by vinyldarkscratch** [comment]
Alrighty, I'll go ahead and remove Prettier then!

**Comment by vinyldarkscratch** [comment]
Fixed by #421.
