### ISSUE TITLE
Stylize pages

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#417]
I was thinking that we should give the homepage, reports page, and individual test completion pages a little bit of styling to make them look more attractive.  What do you think, @foolip?

**Comment by foolip** [comment]
That would be great! The only constraint is that no style should be loaded on test pages before tests are run, and if modern CSS is used it should degrade well enough that the results can still be seen on ancient browsers.

**Comment by vinyldarkscratch** [comment]
Certainly!  I'm thinking that the actual test pages themselves would have no (or little) CSS and no JavaScript dependencies period -- maybe a small media query to set the background dark on dark systems (I'm a _huge_ dark theme fanatic, haha).

**Comment by foolip** [comment]
As long as it's pulled in afterwards to show results, the anything goes I think. This would mean a flash of white before the dark mode kicks in, but I think that's the right trade off for this project.

**Comment by vinyldarkscratch** [comment]
My solution was to add a simple bit of CSS in a `<style>` element first, which changes the background and color so that we don't get that momentary flash.  After the tests are complete, it then programmatically adds the dedicated, larger CSS file to bring in the fancy styling.
