### ISSUE TITLE
Generate endpoints on the fly in backend

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#420]
> Do we need manifest.json separately from test.json, shouldn't the backend be able to derive everything it needs from just the list of tests?

_Originally posted by @foolip in https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484376238_

Additional comments:
https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484440344
https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484450944

**Comment by foolip** [comment]
https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484440344 is the best summary of what I have in mind.

> In short, we structure tests.json more like BCD itself, as a nested object which one would access as `tests.api.Foo.bar.__stuff` as opposed to `tests['api.Foo.bar'].__stuff`. Then, generating a test page is a matter of using the URL pathname to find the right part of tests.json, and then enumerating all tests from that point and outputting them.

**Comment by foolip** [comment]
I'll note that changing tests.json from a list of dot-separated paths to a tree isn't strictly speaking a necessary part of the suggestion. Using the pathname to find the right tests in tests.json is the more important path, to avoid having a parallel manifest.json, and it could be done while still maintaining it as a list.
