### ISSUE TITLE
Collapse tests.json structure

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#430]
> I wonder if this can be collapsed into just `/api/` and `/css/` as the entry points. I get why organizing by the scope makes sense, but as a BCD reviewer I'd want to just go to `/api/Foo/bar` and see the results from all scopes that are applicable. If that can be done, then merging at the highest level should just be a variation of that.
>
> On the same theme, everything should probably be under `/tests/`, so that it's possible to run all tests together if one feels like doing that. Looks like this PR is in an in-between state now?

_Originally posted by @foolip in https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484433617_

**Comment by foolip** [comment]
@vinyldarkscratch commented in https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484626473:

> Collapsing the tests does sound nice, it ends up making the amount of tests in a single file a little too much, causing browser freezes (especially on older browsers). I'm also not sure how to properly hook it up with our report function to submit PRs for all of the data to the results repo. Will have to come back to this one at a later time.

Outputting all tests for a path could be something that we do only while running tests manually, when running all tests we probably want to continue to organize them into a handful of tests split in such a way to make running the tests fast. So I retract my suggestion to try to get rid of that grouping entirely in favor of a single /api/. We could possibly turn it into something like `/api/?scope=Window` however. But let's see where https://github.com/foolip/mdn-bcd-collector/issues/420 will take us first.

**Comment by queengooborg** [comment]
I think it's safe to close this issue -- we've reached our desired goal now and there hasn't been much reason to change the structure of `tests.json` any longer.
