### ISSUE TITLE
Handle prefixes and alternative names

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#431]
> As discussed elsewhere, generating tests for all combinations of prefixes gets to be a bit excessive.
>
> It would be fine to split that change out from this larger change though, no need to fix everything at once.

_Originally posted by @foolip in https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484442442_

Additional comment: https://github.com/foolip/mdn-bcd-collector/pull/416#discussion_r484452152

**Comment by foolip** [comment]
To make sure we're not missing anything we can check against Confluence. `curl https://storage.googleapis.com/web-api-confluence-data-cache/latest/json/org.chromium.apis.web.GridRow.json | jq -r '.[] | .id' | grep -i webkit` should list all the WebKit stuff, for example.

**Comment by vinyldarkscratch** [comment]
All prefixes are no longer being generated, so it's just the raw, unprefixed support now.  Unfortunately, I did take out the code that generates prefixed versions of all the properties based upon prefixes in BCD, so we'll need to add that back for both API and CSS.

**Comment by foolip** [comment]
Our previous approach was to generate tests for paths that don't actually exist in BCD, like `css.properties.-webkit-display`. I think that we'll simplify interpretation of the results if we instead do something like this:

```js
bcd.addTest('api.Element.matches', function() {
  return 'webkitMatchesSelector' in Element.prototype;
}, /* new dictionary: */ {
  alternative_name: 'webkitMatchesSelector'
});
```

In the reports we would store this extra dictionary. It could also make sense to put the "method" used to test in there, and possibly the global scope tested.

Somewhat related to https://github.com/foolip/mdn-bcd-collector/issues/436.

**Comment by gsnedders** [comment]
**Not a Contribution.**

Despite some CSS properties existing with `-apple-` (e.g., `-apple-pay-button-style`) and `-epub-caption-side` in WebKit/Blink, I think by and large we only need the more restricted set of `webkit`/`moz`/`ms` to cover everything (with varying casing for interfaces v. operations/attributes)?

This would be good to increase coverage where things are only supported prefixed (and to be able to show the initial version with support where it was initially prefixed), though would add a substantial number of new tests if runtime is a concern.

**Comment by foolip** [comment]
@vinyldarkscratch did try generating tests for all possible prefixed variants in https://github.com/foolip/mdn-bcd-collector/pull/339, but it increased the size of the tests by enough that the backend exceeded a memory limit and we reverted it in https://github.com/foolip/mdn-bcd-collector/pull/340. I think the approach  suggested in https://github.com/foolip/mdn-bcd-collector/issues/905 is a good one, where we would list only the prefixed properties which we know have been suppored by some browser at some point.

The remaining work will then be to update BCD using those results, which is tracked in https://github.com/foolip/mdn-bcd-collector/issues/431.
