### ISSUE TITLE
Undo weird ESLint max-len formatting

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#432]
After adding and then removing Prettier, we're left with some pretty weird formatting like this:

https://github.com/foolip/mdn-bcd-collector/blob/e91056528d2e23ee01ea4202e936f302cbe8c78b/selenium.js#L29-L34

If find that quite unusual and harder to read than if the `(` and `)` were on the same lines as the conditions. Undoing things like this would be nice. `git grep -E '\($'` finds lines that ends with a `(`, which should be most of these cases.

**Comment by vinyldarkscratch** [comment]
Actually, Prettier was never run on anything that got merged (due to a malformed Prettier confic, my bad).  All the formatting comes from ESLint.

**Comment by foolip** [comment]
Did ESLint automatically wrap things like this with `--fix`? I know that it doesn't require this style, as I undid similar formatting in https://github.com/mdittmer/mdn-confluence/commit/5bc79900baa2e7101bbdb7eda671eee06ed89f13, which did come from running Prettier.

**Comment by vinyldarkscratch** [comment]
Unfortunately `max-len` isn't automatically fixable -- the changes themselves were my own.

**Comment by foolip** [comment]
I see. In that case consider this a low-prio issue to use fewer linebreaks while still satisfying the line length lint. In the quoted case, it still passes lint after collapsing away two lines:
```js
    if ((versionData.status == 'current' || versionData.status == 'retired') &&
      version >= earliestVersion) {
      versions.push(version);
    }
```

**Comment by foolip** [comment]
Seeing this now I don't think it's worth having an open issue about code formatting.
