### ISSUE TITLE
Simplify how we deal with HTTPS

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#435]
Originally, I set things up to run the same tests over both HTTP and HTTPS, thinking that this would allow automating updates of `secure_context_required` in BCD. However, there are only ~25 cases of that in BCD, and it's not worth complicating the collector to deal with.

Instead, I'd suggest running all tests over HTTPS, with the option to use HTTP for localhost and when the browser under test is so old that the certificate used doesn't work. When using those results one would just have to be aware that this might have influenced the results.

**Comment by vinyldarkscratch** [comment]
In #416, I've now simplified the endpoints and removed the `httpsOnly` property (amongst a lot of other things as a part of "main endpoint" removal).  The tests will now load using whatever the current protocol is!

**Comment by foolip** [comment]
Let's just close this, no use in tracking it since https://github.com/foolip/mdn-bcd-collector/pull/416 will land.
