### ISSUE TITLE
Use <datalist> for individual test pages

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#437]
As a follow-up to https://github.com/foolip/mdn-bcd-collector/issues/376, it would be nice to use an `<input list>` with `<datalist>` instead of a `<select>`, as this makes it easier to find the right endpoint by typing part of an API name.

**Comment by vinyldarkscratch** [comment]
Copying over some comments on #376 about `<datalist>`:

Me:
> Looking deeper into `<datalist>`, it appears there's a few issues, especially with cross-browser support. Chrome, Firefox, and Safari each handle the display of entries differently -- Firefox only displays the text, while Safari only displays the value (and seems to cut it off too), though Chrome displays both but cuts the length. It seems that with `<datalist>`, it allows for input other than what's in the list, requiring some JavaScript to validate options. It's certainly quite laggy when typing input too...
> 
> Maybe one thing that could help is limiting the number of options, so it's only the APIs and not their members?

Foolip:
> If it's too demanding on the front end, then we could perhaps have an API for completing a search string on the backend, which will have the complete list of tests loaded into memory at all times.

I'm thinking that a server-side search option would be the best, considering the amount of tests we have, the inconsistency of display with `<datalist>` across browsers, and the lag we've been experiencing.

**Comment by foolip** [comment]
I admit I didn't experiment in all browsers. Inconsistent display seems maybe OK, but how laggy is it?

**Comment by vinyldarkscratch** [comment]
At first, there's about a quarter to a half second delay when typing characters.  However, as the search is narrowed and there's less entries, it gets better.

Regarding the inconsistent display, I have an idea on how to resolve it -- since there are no more main endpoints, we can remove the need for both URL _and_ label, just having the URL be generated by the label.  I'm whipping something up for it now!

**Comment by vinyldarkscratch** [comment]
Good news, I was able to implement something for it, and in turn simplify the tests class -- I also just tested it out on my iPhone, and the way the datalist works performs super well on iOS and iPadOS, hooking into the typing suggestions UI!  It seems that the lag is also only occurring for Chrome now -- Firefox has a little bit of lag when the search results change and there's a lot of them.
