### ISSUE TITLE
Test organization nit: non-unittests in unittest/

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#446]
The unittest/ directory now has a variety of test types, including integration tests in app.js, and some tests using Puppeteer.

The simplest fix is probably to rename the directory? @vinyldarkscratch

**Comment by vinyldarkscratch** [comment]
I consider the server (`app.js`) and `harness.js` (through Puppeteer) to be "units" as well, so I feel the tests properly fall under the "unittest" category (I see Puppeteer as just the test suite to check `harness.js`).  I wouldn't be against renaming the folder, however.  Was there a particular name you had in mind?
