### ISSUE TITLE
Simplify custom tests

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#465]
@vinyldarkscratch as we keep adding these, I think it will be a very common pattern that we have a simple short expression to create the instance. What do you think about a form that takes just the expression, and the generated code would be `'detach' in (document.createNodeIterator(document))` if the expression is simple enough?

We could perhaps run Prettier on the generated code so that we don't need to worry about formatting, like whether we need the extra parenthesis.

__Originally posted by @foolip in https://github.com/foolip/mdn-bcd-collector/pull/459#discussion_r487384762__

**Comment by vinyldarkscratch** [comment]
I'm realizing that the custom code for testing the instance has some slight issues -- by doing `!!instance` rather than `instance !== undefined`, if the instance is `false` or `null` then the test returns `false`, which may present inaccuracies.

**Comment by foolip** [comment]
Creating the instance can fail in multiple ways, both returning the wrong thing or throwing an exception, I think we should let the result of the test be inconclusive (null) in those cases. We can't be sure that the API isn't supported until we understand the failure.

Often, just trying to use the instance and letting an exception be thrown will take care of this in a compact way. Sometimes a typeof check might be needed, but even that is risky, as there's been a conflation of "object" and "function " for some things (interface objects I think) historically.
