### ISSUE TITLE
Selenium + IE/Edge: GitHub export returns HTTP 411

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#468]
The XMLHttpRequest for posting to the GitHub export returns a 411 error code when testing with Selenium.  It appears that a `Content-Length` header must be defined...which is odd, considering it works normally (non-Selenium) on the same test suite.

**Comment by foolip** [comment]
Which versions of Edge does this affect? If you change the reporting to use `fetch()` instead, does the problem persist?

**Comment by vinyldarkscratch** [comment]
This affects all non-Blink versions of Edge, from what I've seen (and it may be affecting IE as well, though I haven't confirmed this).  Lemme give that suggestion a shot and see what the result is!

**Comment by foolip** [comment]
Are you running with any kind of proxying, or does the Selenium script use http://mdn-bcd-collector.appspot.com/ directly? If there's proxying of requests involved, maybe one of the proxy layers are to blame. Just a guess, though.

**Comment by vinyldarkscratch** [comment]
The Selenium script isn't particularly configured to use any form of proxy layer, but looking at the request headers, a `Content-Length` IS being sent (it's set to `0`).  Seeing the response headers, it states the response is via "Jetty", so I guess it _is_ going through a proxy.

Though that makes me wonder...  Why is it failing just for Trident (IE) and EdgeHTML?  Why isn't it failing for other browsers like Chrome?

(P.S. confirmed the same issue is occurring with Internet Explorer.)

**Comment by foolip** [comment]
The implementation of WebDriver (https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/) might be somehow involved here, if controlling the browsers via WebDriver causes them to take different code paths at some points. But that again is just a guess.

**Comment by vinyldarkscratch** [comment]
Dropping this down to medium priority since it can be worked around for now (by running manually).
