### ISSUE TITLE
Formatting for non-JavaScript files

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#488]
Inspired by #485.  ESLint is great for formatting the JavaScript files, but for all the others, it has no support.  We should find and introduce a package that can format our other files, like the Markdown, JSON, YAML, and EJS files.

In my research, I found a package called [Unibeautify](https://unibeautify.com/) that has support for many different beautifiers and many different languages.  It may be something to look into to simplify our code/file formatting!  It also links to the beautifiers it has support for, and has a matrix of the languages it supports to the beautifiers that can handle them: https://unibeautify.com/docs/languages

**Comment by vinyldarkscratch** [comment]
#509 and #510 have taken care of the Markdown, JSON, and YAML, leaving only the EJS files.  Unibeautify __does__ seem like a nice project (I'll probably end up contributing to it in my spare time, haha), but it's got some big flaws to work out before it can be used.  Perhaps the individual linters it works with may be worth looking into...
