### ISSUE TITLE
Support SharedWorkerGlobalScope

### ISSUE THREAD

**Issue by saschanaz** [foolip/mdn-bcd-collector#512]
It seems there should also be `runSharedWorker()` in harness.js.

**Comment by foolip** [comment]
Are there any entries in BCD about support in shared workers specifically, or any APIs that are only exposed in shared workers? My guess for these questions has been no, and that's why I haven't suggested this.

**Comment by saschanaz** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/SharedWorkerGlobalScope/close says `.close()` is not supported on Chrome. I was too lazy to write some script to test it, so I opened this.

**Comment by vinyldarkscratch** [comment]
It does seem that Shared Workers have some additional support/functionality than Dedicated Workers do, based upon the MDN web docs.  It seems like it would be simple enough to add Shared Worker support -- just duplicate the regular worker code and modify use a `SharedWorker` instead!

**Comment by vinyldarkscratch** [comment]
Fixed by #550.
