### ISSUE TITLE
Auto-update prod branch on version bump

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#576]
Just had a thought about having a GitHub Action to automatically update the production version when we bump the version number.  I think this will present better release control practices so that we don't change behavior or test results without changing the version number.

**Comment by foolip** [comment]
If we want to enforce a new version for every prod push and don't mind churning the version number a lot (which I think we shouldn't mind) then the easiest setup is probably to use version tags, and deploy on tag push. We'd then just get rid of the prod branch.

**Comment by queengooborg** [comment]
Closing since we had gotten this logic taken care of when we were still deploying to GAE.
