### ISSUE TITLE
Case-insensitive URLs?

### ISSUE THREAD

**Issue by vinyldarkscratch** [foolip/mdn-bcd-collector#582]
A very little thing, but it might be nice to have case-insensitive URLs for the tests?  Or more accurately, redirects the URL to the proper casing.  (I've been manually typing out the URLs quite a bit lately and end up accidentally forgetting to capitalize the API name.)

**Comment by foolip** [comment]
I'd like this as I've also typed URLs manually. One wrinkle is that `window.defaultstatus` and `window.defaultStatus` both exist, and there may be other case-insensitive duplicates.

However, one could still make this work. First try a case-sensitive match. If there is none, but there is a case-insensitive match, then redirect to that. The redirecting will make it easier to then copy the correct URL.

**Comment by vinyldarkscratch** [comment]
Follow-up idea: on the 404 page that shows up when it can't find a test, we could perhaps include a small list of suggestions in the case of typos?

**Comment by foolip** [comment]
Yep, that would work! If you don't often rely on ignoring the capitalization that could perhaps be the only solution to the problem.
