### ISSUE TITLE
Don't submit results when visiting manually

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#584]
Visiting a page like http://mdn-bcd-collector.appspot.com/tests/api/Document/createAttributeNS, submitting the results to the server isn't really useful. Rather it takes time and causes the layout of the results page to flicker through some different stages.

We could have a special URL for when we want to submit the results, like appending #bla=something.

**Comment by foolip** [comment]
I'm filing this also because submitting the results is something that can go wrong. http://mdn-bcd-collector.appspot.com/tests/api/Document/createAttributeNS doesn't show the results in IE8, but probably would if it didn't try to submit results. By avoiding that one can test manually going back to even older browsers.

**Comment by vinyldarkscratch** [comment]
#586 should help with some of the results submission stuff and results display in IE8 (haven't confirmed this), but yeah, having a URL argument to toggle server submission would be helpful.

**Comment by queengooborg** [comment]
We've already implemented this, so closing.
