### ISSUE TITLE
Unable to upload results on Chrome for Android

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#632]
This is https://github.com/foolip/mdn-bcd-collector/issues/486 again, but failing on Chrome for Android:
<img src=https://user-images.githubusercontent.com/498917/96613773-a50d3a00-12ff-11eb-9403-cc38e160a2c8.png width=374 height=758>

The console error is:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at report (harness.js:436)
    at harness.js:351
    at MessagePort.messageChannel.port1.onmessage (harness.js:293)
```

So the failure is here:
https://github.com/foolip/mdn-bcd-collector/blob/743d92c1ee0a61061d52e299b3cd0a8cac0af7fc/static/resources/harness.js#L436

Presumably the fix is simple. We should also have some kind of regression testing in place so that it doesn't keep breaking on mobile.

**Comment by foolip** [comment]
Checking "hide results" fixes the problem because this code then isn't run at all. A failure to pretty-print the results shouldn't be able to prevent the results from being submitted, so some isolation between these two things is needed. Pretty printing should happen after results have been successfully submitted, to be entirely on the safe side about interfering with it.

**Comment by foolip** [comment]
@vinyldarkscratch I guess there's still a bug left that the results don't shown ok Android, right?

**Comment by vinyldarkscratch** [comment]
It looks like this was a result of attempting to render code for results that didn't actually have any code to show, specifically lack of service workers.  In #633, I added a little clause to not render a code block if there isn't any code to show -- a quick check with an added console log showing what would be affected by this, and confirmed it's only the things that wouldn't have code to show!

What surprises me is that it only became a problem recently, and hasn't been a problem in other browsers, including Chrome Desktop...

**Comment by foolip** [comment]
I discovered this while trying out the collector on Facebook's WebView-based browser with a colleague. Although that isn't what I posted the screenshot of. Are you sure the collector has recently been working in various mobile browsers? Do we need to add CI tests to ensure it doesn't break again?

**Comment by vinyldarkscratch** [comment]
I've seen it post the results successfully when running the tests.  Alas, I'm not certain why this issue would have affected only mobile browser, hmmm...

**Comment by foolip** [comment]
I'll reopen to verify with https://github.com/foolip/mdn-bcd-collector/pull/637 deployed that it works end-to-end with at least Chrome for Android, Samsung Internet and Safari on iOS.

**Comment by vinyldarkscratch** [comment]
Good news: no problems in the latest of Chrome, Firefox, Opera, or Samsung Internet on Android, nor Safari iOS/iPadOS!

<details>
<summary>Screenshots</summary>
<img width="726" alt="Screen Shot 2020-10-24 at 05 56 22" src="https://user-images.githubusercontent.com/5179191/97082425-6e187c00-15be-11eb-9618-b329261a8843.png">
<img width="726" alt="Screen Shot 2020-10-24 at 05 57 05" src="https://user-images.githubusercontent.com/5179191/97082427-72449980-15be-11eb-8614-817d41959913.png">
<img width="726" alt="Screen Shot 2020-10-24 at 05 58 26" src="https://user-images.githubusercontent.com/5179191/97082428-7375c680-15be-11eb-92d5-3f13fd68f909.png">
<img width="726" alt="Screen Shot 2020-10-24 at 05 59 19" src="https://user-images.githubusercontent.com/5179191/97082430-74a6f380-15be-11eb-80d2-dda5a081b28b.png">
<img width="726" alt="IMG_153DE25DB04E-1" src="https://user-images.githubusercontent.com/5179191/97082434-753f8a00-15be-11eb-9804-2802c1d548f3.jpeg">
</details>

**Comment by foolip** [comment]
Great, thanks for verifying!
