### ISSUE TITLE
Ignore "false" if existing version_added is for version newer than our data has

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#659]
Something I noticed is that `update-bcd` will overwrite a `version_added` with `false` if our data doesn't extend to browser versions high enough (example: our results has Safari 10-13, but a feature was added in Safari 14 -- the script says it is `false`).

**Comment by foolip** [comment]
I believe that if we take the approach of looking for contradictions between the data we have and BCD and making updates to resolve those, then we couldn't have this problem, because there's no contradiction between the collector results and BCD to begin with, only incomplete collector results.
