### ISSUE TITLE
Check support for each CSS property keyword value

### ISSUE THREAD

**Issue by saschanaz** [foolip/mdn-bcd-collector#705]
Currently the code only checks existence of properties but not the property values. We can probably extract the supported keywords from webref and use `CSS.supports` to check it.

**Comment by foolip** [comment]
This should indeed be possible, and will allow us to cover a lot more of the css.properties.*.* entries. I think not all of those are for keywords, but it's probably safe to assume that matching entries are for keywords.

**Comment by gsnedders** [comment]
**Not a Contribution.**

#36 and #431 are also kinda relevant here, given there's a fair bit of prefixed keyword values out there.

**Comment by foolip** [comment]
Good point. I suppose that for keywords there's no introspection mechanism, and that we'd have to get a list from files like [css_value_keywords.json5](https://source.chromium.org/chromium/chromium/src/+/master:third_party/blink/renderer/core/css/css_value_keywords.json5;drc=e2d60fb99b79a70cae4c675a0524fcd915f12e97) and [CSSValueKeywords.in](https://trac.webkit.org/browser/webkit/trunk/Source/WebCore/css/CSSValueKeywords.in?rev=271606). Or is there a way that I don't know about?

**Comment by foolip** [comment]
I gave this a try based on the new https://www.npmjs.com/package/@webref/css package using the simplest approach that only detect keywords used directly in the property definition, not indirectly via value spaces like `<display-inside>`.

That generated over 1000 new tests, but only about 100 were entries in BCD. It's probably usually the case that documenting support for specific keywords isn't that useful, it's only when support for a keyword came after the property itself as in `display: grid` that it's useful. Generating tests for the majority of cases where that wasn't the case is going to create a long burndown list of missing BCD entries that I'm not sure what I'd do with.

**Comment by gsnedders** [comment]
> I gave this a try based on the new https://www.npmjs.com/package/@webref/css package using the simplest approach that only detect keywords used directly in the property definition, not indirectly via value spaces like `<display-inside>`.
> 
> That generated over 1000 new tests, but only about 100 were entries in BCD. It's probably usually the case that documenting support for specific keywords isn't that useful, it's only when support for a keyword came after the property itself as in `display: grid` that it's useful. Generating tests for the majority of cases where that wasn't the case is going to create a long burndown list of missing BCD entries that I'm not sure what I'd do with.

Did you push this anywhere? I'd be curious to see if—despite the large number of new tests—whether it created any changes to the data (esp. for current browsers).
