### ISSUE TITLE
MDI icons don't show up in some older browsers

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#741]
In older browsers, the MDI icons show up with weird symbols, blank squares, or sometimes, not at all.  We should try to maximize their compatibility somehow.

**Comment by foolip** [comment]
What is MDI, do you mean the favicon?

**Comment by vinyldarkscratch** [comment]
MDI (Material Design Icons) is what we use for the icons on the page, like the heart for "love", or the GitHub logo.  It's a font family, which older browsers don't like quite as much.

MDI also has SVG alternatives, so I'm thinking we could use them instead, and, like the browser logos, only obtain what we need.

**Comment by foolip** [comment]
If it's just how the front page looks, then I don't think that needs to look right on old browsers as long as running the tests works.
