### ISSUE TITLE
Add a "compiled results" page?

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#775]
I was reading through the email thread about getting BrowserStack on board, and I noticed a statement suggesting a test run in various browsers, displaying the results.  If you think about it, this project pretty much does just that, with the aid of the Selenium script run (which uses BrowserStack).  What if we were to add a page that displays all of the results our collector has obtained in some form of CanIUse-looking interface?  We could then include links to them, like `/results/api/Document`, which displays the test code run and the results our collector has obtained?

**Comment by foolip** [comment]
A variation of this which would have use beyond the collector is a way to render BCD itself independent from MDN. We could then use that for the collector results as well, perhaps showing what BCD would look like if we applied all of the changes.

I think calling this an enhancement is appropriate, though, as having this view isn't essential for us to understand the results and update BCD.

**Comment by foolip** [comment]
https://github.com/mdn/yari/tree/master/client/src/document/ingredients/browser-compatibility-table is some code for rendering BCD tables that I came across today. Not sure if that can be reused though.

**Comment by foolip** [comment]
And https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/ explains what Yari is.
