### ISSUE TITLE
Add testing support for event APIs?

### ISSUE THREAD

**Issue by queengooborg** [foolip/mdn-bcd-collector#799]
Many/most of the event APIs are typically not exposed on their own, and will need to be tested by firing the event itself.  In 6b210c224e83b9ec3a2312575755068dd015a705, I had disabled the event APIs to ensure that we are not submitting bad data.  If we want to add data for event APIs, we will need to figure out some way to fire and catch the events.

**Comment by foolip** [comment]
For event interfaces introduced in specs now, I think it's safe to assume they will be exposed, as `[NoInterfaceObject]` is no longer common practice. For all historical data, however, it is important to untangle 3 different things:
- can the engine fire an event named "foo"
- is there an "onfoo" event handler attributes somewhere
- does that event use the `Event` interface or some specialized `FooEvent`, and was its interface object exposed?

It's a lot to untangle, unfortunately.

**Comment by foolip** [comment]
I added back the tests for event interfaces in https://github.com/foolip/mdn-bcd-collector/pull/924.

The missing piece here is is updating `foo_event` entries for whether the events actually fire.
