### ISSUE TITLE
Issue with getting exposure for DedicatedWorker

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#815]
@vinyldarkscratch in https://github.com/mdn/browser-compat-data/pull/7447#discussion_r529204571:

> It looks like there's an issue with getting exposure for `DedicatedWorker`, so because it was only testing in shared workers, which is not supported in IE

I don't know what the issue is exactly, but filing this to track it in the collector.

**Comment by vinyldarkscratch** [comment]
Oh oops, I forgot to link the PR, sorry!  I actually fixed this in #811, and will get a new collector version deployed soon!

**Comment by foolip** [comment]
I see, thanks! When fixing something in the collector as a result of a review over in BCD, it would be great to link it for discoverability.
