### ISSUE TITLE
Ignore custom instance for static attributes, methods and constants

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#825]
The way that https://github.com/foolip/mdn-bcd-collector/pull/809 fixed an incorrect tests suggests that we generate the wrong code by default if there's custom code for getting an instance, and would have to override that for every static attribute, method and constant.

Instead, can we just ignore the code for getting an instance where we don't need an instance?

**Comment by foolip** [comment]
By searching for "static" in https://github.com/w3c/webref/tree/master/ed/idl I could spot at least these broken cases:
http://mdn-bcd-collector.appspot.com/tests/api/Notification/maxActions
http://mdn-bcd-collector.appspot.com/tests/api/Request/redirect

**Comment by foolip** [comment]
It seems like the fix didn't handle all the cases, at least this one is still using the instance:
http://staging-dot-mdn-bcd-collector.appspot.com/tests/api/Request/redirect

**Comment by vinyldarkscratch** [comment]
Request.redirect isn't a static attribute, however:

```webidl
interface Request {
  readonly attribute RequestRedirect redirect;
}
```
