### ISSUE TITLE
Report lacks FetchEvent

### ISSUE THREAD

**Issue by saschanaz** [foolip/mdn-bcd-collector#867]
It seems the service worker exposure test does not include all applicable entries.

**Comment by saschanaz** [comment]
https://github.com/foolip/mdn-bcd-collector/blob/b0f41f7964744a634de58bde2fe68a0f33392755/build.js#L592-L596

Seems it's intentional, but I think an option would be helpful (for me to manually check the existence).

**Comment by vinyldarkscratch** [comment]
Event APIs are currently ignored since most of them are not exposed by default.  See #799.

**Comment by saschanaz** [comment]
Thanks, closing as duplicated

**Comment by foolip** [comment]
While lots of event interfaces have historically not been exposed, I think we should still test for them. For any recent additions to the platform we will not be misled, as *not* exposing the interface object now requires extra work, and I expect very rarely happens.

The update-bcd script could still have an option to ignore event interfaces, perhaps.

**Comment by foolip** [comment]
`FetchEvent` is now tested: https://mdn-bcd-collector.appspot.com/tests/api/FetchEvent
