### ISSUE TITLE
Use Web API Confluence as a source of CSS properties

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#905]
**Not a Contribution.**

Similar to #36, it would be potentially interesting to use a set of properties derived from what Confluence has as properties on `CSSStyleDeclaration`. This will need _some_ manual curation (to exclude other attributes/operations), and note that WebKit and forks (inc. Blink) will run into https://bugs.webkit.org/show_bug.cgi?id=217623 and https://bugs.webkit.org/show_bug.cgi?id=217627, though it does at least have many prefixed forms present (see also #431).

**Comment by foolip** [comment]
Good idea, @gsnedders!

I'd like to go through the full set of Confluence APIs and make sure everything is either in BCD or shouldn't be. I think doing that manually as a one-off should suffice. If we wanted to check if browsers add things not in BCD on an ongoing basis, I'd probably handle that differently, most likely with simple test page that has a list of BCD paths, and looks for interfaces etc. which aren't in that list.

This is all in light of a desire to not maintain Confluence indefinitely, but rather make sure BCD covers it all and then using BCD as a replacement.

**Comment by foolip** [comment]
I've added lots more CSS properties now. A few newly generated tests that show support in Safari:
https://staging-dot-mdn-bcd-collector.appspot.com/tests/css/properties/-apple-color-filter
https://staging-dot-mdn-bcd-collector.appspot.com/tests/css/properties/-webkit-aspect-ratio

I think that `-webkit-aspect-ratio` actually doesn't do anything, which highlight the pitfalls of using feature detection for CSS properties. Any updates of the BCD data needs to consider whether it really worked as well.
