### ISSUE TITLE
WorkerNavigator test results suspicious for Chrome 42/43 

### ISSUE THREAD

**Issue by foolip** [foolip/mdn-bcd-collector#960]
https://mdn-bcd-collector.appspot.com/tests/api/WorkerNavigator results for Chrome 42 and 43 make me suspect the test is wrong.

The api.WorkerNavigator tests true in both, but the subfeatures are all false in 42, while a bunch are true in 43. It doesn't make sense that the interface itself would have been there in Chrome 42 with no members.

Maybe tests throwing exceptions is handled incorrectly in workers?

In any case, this should generate tests like `"hardwareConcurrency" in navigator` in workers as well as window contexts.

**Comment by queengooborg** [comment]
Looks like this one's been fixed with a custom test.
