### ISSUE TITLE
Local export

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#976]
At least from a quick glance, it's not clear how to download a JSON comparable to what would be uploaded to GitHub, especially if you're running the server locally.

**Comment by foolip** [comment]
This is kind of possible already. If you click "Submit to GitHub" and see that fail, there's then a "Download results JSON" link to `/api/results`. You won't get the same filename, but `update-bcd.js` doesn't care about the filenames so you should be able to use the results.

But this is kind of an accidental feature, I'd like to do better. I'm tinkering in https://github.com/foolip/mdn-bcd-collector/pull/979 with something that would save files to the local filesystem. It doesn't work yet though.

**Comment by foolip** [comment]
@gsnedders is the behavior of https://staging-dot-mdn-bcd-collector.appspot.com/ good enough now?

Before the next release I need to fix the Selenium script as well, but it should already be possible to run this locally.
