### ISSUE TITLE
Add local HTTPS server mode

### ISSUE THREAD

**Issue by gsnedders** [foolip/mdn-bcd-collector#986]
Presumably this should add some option to app.js to opt-in to serving on HTTPS, probably with an option to point at a pre-created certificate or falling back to generating its own certificate (at least on first run).

**Comment by foolip** [comment]
This is looking more and more like WPT :)

Would this be to test some older browsers that don't treat localhost as secure context, or why is it important to test HTTPS locally?

**Comment by gsnedders** [comment]
> Would this be to test some older browsers that don't treat localhost as secure context, or why is it important to test HTTPS locally?

Mostly being able to point VMs at a local instance (on a private-use IP), and having them run on a secure context.

**Comment by foolip** [comment]
I see, that makes sense. So the certificate would be one that the VM trusts, either because it's installed in the VM or (to avoid that) the cert is simply a valid cert for a real domain used for testing purposes.

The work should be the same regardless. I haven't looked into what crypto support in node looks like, but hopefully this can be done without putting nginx or similar in front.

**Comment by foolip** [comment]
I gave this a try and it was much easier than I thought. I did https://github.com/foolip/mdn-bcd-collector/pull/1046 using the WPT cert and got it working. @gsnedders do you have any preferences for what the opt-in should look like? Would having the `HTTPS_PORT` environment variable be the opt-in work?

**Comment by foolip** [comment]
I've realized that using `HTTPS_PORT` as the opt-in doesn't make sense, one still has to point to cert/key files, and that would make sense as the opt-in. Maybe putting them in a `config.json` would work.

**Comment by gsnedders** [comment]
I'd have expected a CLI argument for it?

**Comment by foolip** [comment]
Sure, that's the easiest to implement, so let's go with that.

**Comment by foolip** [comment]
OK, now the following should work:
> npm start -- --https-cert=$HOME/web-platform-tests/wpt/tools/certs/web-platform.test.pem --https-key=$HOME/web-platform-tests/wpt/tools/certs/web-platform.test.key

With that and the `security add-trusted-cert` thing in wpt docs, I can access https://web-platform.test:8443 in Safari.
